project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - ads.txt

website:
  title: "Vectoring AI"
  description: "AI For Everyone: Insights, Tutorials, and Curated Resources on LLMs, RAG, Agents, and More."
  site-url: https://vectoringai.com/
  # navbar:
  #   background: primary
  #   left: 
  #     - text: "Home"
  #       file: index.qmd

  #     - text: "About"
  #       file: pages/about.qmd
  #   right:
  #     - icon: github
  #       href: https://github.com/VectoringAI
  sidebar:
    tools: 
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/tanquangduong/
      - icon: github
        href: https://github.com/VectoringAI
    style: "docked"
    contents:
      - text: "Home"
        file: index.qmd
      - section: "AI Engineering"
        contents:
          - pages/llm.qmd
          - pages/agent.qmd
          - pages/rag.qmd
          - pages/benchmark.qmd
          - pages/milestone.qmd
          # - pages/article.qmd
      # - section: "Made with AI"
      #   contents:
      #     - pages/vaitalk.qmd
      - text: "About"
        file: pages/about.qmd
      
    
  favicon: /images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} 2025-2026 Vectoring AI. All rights reserved. | [Privacy Policy](/pages/privacy.html)" 
  
format:
  html:
    include-in-header:
      - adsense.html
      - cookieconsent.html
    page-layout: article
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: false