project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - ads.txt
    - robots.txt
    - sw.js
    - images/logo_vectoringai_180.png

author:
  name: "Vectoring AI"
  url: https://vectoringai.com/pages/about.html

website:
  title: "Vectoring AI"
  description: "AI For Everyone: Insights, Tutorials, and Curated Resources on LLMs, RAG, Agents, and More."
  site-url: https://vectoringai.com
  google-analytics: "G-Q4RQ337R0F"
  # navbar:
  #   background: primary
  #   left: 
  #     - text: "Home"
  #       file: index.qmd

  #     - text: "About"
  #       file: pages/about.qmd
  #   right:
  #     - icon: github
  #       href: https://github.com/VectoringAI
  sidebar:
    tools: 
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/tanquangduong/
      - icon: github
        href: https://github.com/VectoringAI
      - icon: youtube
        href: https://www.youtube.com/@vectoringai
    style: "docked"
    contents:
      - text: "**Home**"
        file: index.qmd
      - section: "**AI Engineering**"
        contents:
          - text: "LLMs"
            file: pages/llm.qmd
          - text: "Agents"
            file: pages/agent.qmd
          - text: "RAG"
            file: pages/rag.qmd
          - text: "Benchmarks"
            file: pages/benchmark.qmd
          - text: "Milestones"
            file: pages/milestone.qmd
      - section: "**AI Interview**"
        contents:
          - text: "ML Interview"
            file: pages/ml-interview.qmd
          - text: "LLM Interview"
            file: pages/llm-interview.qmd
          - text: "SWE Interview"
            file: pages/swe-interview.qmd
          - text: "AIOps Interview"
            file: pages/aiops-interview.qmd
          - text: "Design Pattern"
            file: pages/design-pattern.qmd
          - text: "System Design"
            file: pages/system-design.qmd
          - text: "AI Architect"
            file: pages/ai-architect.qmd
          
          # - pages/article.qmd
      - section: "**Made by VAI**"
        contents:
          - text: "VaiTalk"
            file: pages/vaitalk.qmd
      - text: "**About**"
        file: pages/about.qmd
      
    
  favicon: /images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} 2025-2026 Vectoring AI. All rights reserved. | [Privacy Policy](/pages/privacy.html)" 
  
format:
  html:
    include-in-header:
      - adsense.html
      - cookieconsent.html
      - share-buttons.html
      - canonical.html
      - jsonld.html
      - sidebar-logo.html
      - monetag.html
    include-after-body:
      - infolinks.html
      - mobile-menu-fab.html
      - top-animation.html
    page-layout: article
    date-format: "DD MMMM YYYY"
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: false