project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Vectoring AI"
  description: "AI For Everyone: Insights, Tutorials, and Curated Resources on LLMs, RAG, Agents, and More."
  site-url: https://vectoringai.com/
  # navbar:
  #   background: primary
  #   left: 
  #     - text: "LLM"
  #       file: index.qmd

  #     - text: "About"
  #       file: about.qmd
  #   right:
  #     - icon: linkedin
  #       href: https://www.linkedin.com/in/tanquangduong/
  #     - icon: github
  #       href: https://github.com/tanquangduong
  sidebar:
    logo: "/images/logo_vectoringai_512.png"
    tools: 
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/tanquangduong/
      - icon: github
        href: https://github.com/VectoringAI
    style: "docked"
    contents:
      - section: "AI Engineering"
        contents:
          - index.qmd
          - pages/agent.qmd
          - pages/rag.qmd
          # - pages/stack.qmd
          # - pages/article.qmd
      
    
  favicon: /images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} Copyright 2025, Vectoring AI. All rights reserved." 
  
format:
  html:
    page-layout: article
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: false