<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-09-15">

<title>Vending-Bench – Vectoring AI</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../..//images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dbc92dda8186f57fa2e333fbb71d6a9d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b981e3f33a8ad6ba97cc0b6118e04959.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9738638303661485" crossorigin="anonymous"></script>
<!-- Cookie Consent Banner (GDPR compliant) -->
<style>
#cookie-consent-banner {
  display: none;
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #1d1d1d !important;
  color: #ffffff !important;
  padding: 16px 24px;
  z-index: 9999;
  font-size: 14px;
  box-shadow: 0 -2px 10px rgba(0,0,0,0.3);
}
#cookie-consent-banner p {
  margin: 0 0 12px 0;
  line-height: 1.5;
  color: #ffffff !important;
}
#cookie-consent-banner a {
  color: #78b9ff;
  text-decoration: underline;
}
#cookie-consent-buttons {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}
#cookie-consent-buttons button {
  padding: 8px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: 600;
}
#btn-accept-all {
  background: #3B70FE;
  color: #fff;
}
#btn-accept-essential {
  background: #555;
  color: #fff;
}
#btn-deny {
  background: transparent;
  color: #ccc;
  border: 1px solid #666 !important;
}
</style>

<meta property="og:title" content="Vending-Bench – Vectoring AI">
<meta property="og:description" content="A long-horizon benchmark that tests whether LLM agents can coherently operate a vending machine business over months of simulated time">
<meta property="og:image" content="https://vectoringai.com//images/benchmark/vending-bench-300px.png">
<meta property="og:site_name" content="Vectoring AI">
<meta property="og:image:height" content="200">
<meta property="og:image:width" content="300">
<meta name="twitter:title" content="Vending-Bench – Vectoring AI">
<meta name="twitter:description" content="A long-horizon benchmark that tests whether LLM agents can coherently operate a vending machine business over months of simulated time">
<meta name="twitter:image" content="https://vectoringai.com//images/benchmark/vending-bench-300px.png">
<meta name="twitter:image-height" content="200">
<meta name="twitter:image-width" content="300">
<meta name="twitter:card" content="summary_large_image">
</head><body class="nav-sidebar docked quarto-light"><div id="cookie-consent-banner">
  <p>We use cookies to serve personalized ads (Google AdSense) and analyze traffic.
    You can accept all cookies, accept only essential cookies, or deny non-essential cookies.
    <a href="../../pages/privacy.html">Privacy Policy</a>
  </p>
  <div id="cookie-consent-buttons">
    <button id="btn-accept-all">Accept All</button>
    <button id="btn-accept-essential">Essential Only</button>
    <button id="btn-deny">Deny</button>
  </div>
</div>

<script>
(function() {
  var consent = localStorage.getItem("cookie_consent");

  function loadAdSense() {
    if (document.querySelector('script[src*="adsbygoogle"]')) return;
    var s = document.createElement("script");
    s.async = true;
    s.src = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9738638303661485";
    s.crossOrigin = "anonymous";
    document.head.appendChild(s);
  }

  function showBanner() {
    document.getElementById("cookie-consent-banner").style.display = "block";
  }

  function hideBanner() {
    document.getElementById("cookie-consent-banner").style.display = "none";
  }

  if (consent === "all") {
    loadAdSense();
  } else if (consent === "essential" || consent === "denied") {
    // Do not load AdSense
  } else {
    // No choice made yet — show banner, do not load AdSense
    window.addEventListener("DOMContentLoaded", showBanner);
  }

  window.addEventListener("DOMContentLoaded", function() {
    document.getElementById("btn-accept-all").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "all");
      hideBanner();
      loadAdSense();
    });
    document.getElementById("btn-accept-essential").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "essential");
      hideBanner();
    });
    document.getElementById("btn-deny").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "denied");
      hideBanner();
    });
  });
})();
</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Vectoring AI
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Vectoring AI</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/VectoringAI" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.youtube.com/@vectoringai" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-youtube"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">AI Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/agent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Agent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/rag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RAG</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/benchmark.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI Benchmark</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/milestone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI Milestones</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title"><strong>Sections</strong></h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#what-is-vending-bench" id="toc-what-is-vending-bench" class="nav-link" data-scroll-target="#what-is-vending-bench">What Is Vending-Bench?</a></li>
  <li><a href="#who-built-it" id="toc-who-built-it" class="nav-link" data-scroll-target="#who-built-it">Who Built It?</a></li>
  <li><a href="#what-skills-does-it-test" id="toc-what-skills-does-it-test" class="nav-link" data-scroll-target="#what-skills-does-it-test">What Skills Does It Test?</a></li>
  <li><a href="#current-leaderboard" id="toc-current-leaderboard" class="nav-link" data-scroll-target="#current-leaderboard">Current Leaderboard</a></li>
  <li><a href="#where-to-explore-the-benchmark" id="toc-where-to-explore-the-benchmark" class="nav-link" data-scroll-target="#where-to-explore-the-benchmark">Where to Explore the Benchmark</a></li>
  <li><a href="#understanding-the-metrics" id="toc-understanding-the-metrics" class="nav-link" data-scroll-target="#understanding-the-metrics">Understanding the Metrics</a></li>
  <li><a href="#why-vending-bench-matters" id="toc-why-vending-bench-matters" class="nav-link" data-scroll-target="#why-vending-bench-matters">Why Vending-Bench Matters</a></li>
  <li><a href="#video-vending-bench-explained" id="toc-video-vending-bench-explained" class="nav-link" data-scroll-target="#video-vending-bench-explained">Video: Vending-Bench Explained</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#read-more" id="toc-read-more" class="nav-link" data-scroll-target="#read-more">Read More</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Vending-Bench</h1>
<p class="subtitle lead">A long-horizon benchmark that tests whether LLM agents can coherently operate a vending machine business over months of simulated time</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Keywords:</strong> Vending-Bench, long-term coherence, AI agent benchmark, LLM evaluation, autonomous agents, vending machine simulation, business management, context window, meltdown loops, AI safety, Andon Labs, inspect-ai</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../images/benchmark/vending-bench-300px.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="300"></p>
</figure>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>LLMs can ace exams, write code, and even pass medical licensing tests. But can they run a simple business for more than a few days without losing their minds?</p>
<p><strong>Vending-Bench</strong> is a simulated environment that tests an LLM agent’s <strong>long-term coherence</strong> — its ability to maintain rational, consistent behavior over extended time horizons. The task is deceptively simple: operate a vending machine. Buy products from suppliers, stock the machine, set prices, collect earnings, and pay a $2 daily fee. Each sub-task is trivial, but over <strong>200+ simulated days</strong> and <strong>&gt;20 million tokens per run</strong>, even the best models eventually derail — misinterpreting delivery schedules, forgetting orders, or descending into spectacular “meltdown” loops from which they rarely recover.</p>
<blockquote class="blockquote">
<p>“While Large Language Models can exhibit impressive proficiency in isolated, short-term tasks, they often fail to maintain coherent performance over longer time horizons.” — Backlund &amp; Petersson, arXiv:2502.15840</p>
</blockquote>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["Short-term Benchmarks&lt;br/&gt;(HumanEval, MMLU, etc.)&lt;br/&gt;Isolated tasks"] --&gt; B["Models score&lt;br/&gt;impressively"]
    B --&gt; C["Give them a long-running&lt;br/&gt;business to manage..."]
    C --&gt; D["Vending-Bench&lt;br/&gt;&gt;20M tokens per run&lt;br/&gt;Models derail"]

    style A fill:#e74c3c,stroke:#333,color:#fff
    style B fill:#f39c12,stroke:#333,color:#fff
    style C fill:#27ae60,stroke:#333,color:#fff
    style D fill:#3498db,stroke:#333,color:#fff
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="what-is-vending-bench" class="level2">
<h2 class="anchored" data-anchor-id="what-is-vending-bench">What Is Vending-Bench?</h2>
<p><strong>Vending-Bench</strong> is an agent benchmark where an LLM operates a vending machine business in a richly simulated environment. The agent starts with <strong>$500</strong>, faces a <strong>$2/day operating fee</strong>, and must turn a profit by sourcing products from real-world wholesalers (via simulated email), stocking a 4-row vending machine, setting competitive prices, and collecting earnings — all while customer demand fluctuates with day-of-week, weather, and product variety.</p>
<p>The simulation runs for up to <strong>2,000 agent messages</strong> (typically 150–220 simulated days), consuming <strong>~25 million tokens</strong> and taking <strong>5–10 real-world hours</strong> per run. Each model is tested across <strong>5 independent runs</strong> to measure variance.</p>
<section id="key-characteristics" class="level3">
<h3 class="anchored" data-anchor-id="key-characteristics">Key Characteristics</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Task</strong></td>
<td>Operate a vending machine business (ordering, stocking, pricing, cash collection)</td>
</tr>
<tr class="even">
<td><strong>Duration</strong></td>
<td>Up to 2,000 messages / 150–220 simulated days per run</td>
</tr>
<tr class="odd">
<td><strong>Token consumption</strong></td>
<td>~25 million tokens per run</td>
</tr>
<tr class="even">
<td><strong>Starting capital</strong></td>
<td>$500</td>
</tr>
<tr class="odd">
<td><strong>Daily fee</strong></td>
<td>$2</td>
</tr>
<tr class="even">
<td><strong>Runs per model</strong></td>
<td>5 (to measure variance)</td>
</tr>
<tr class="odd">
<td><strong>Primary metric</strong></td>
<td><strong>Net worth</strong> at end of simulation (cash + inventory value)</td>
</tr>
<tr class="even">
<td><strong>Framework</strong></td>
<td>AISI’s <a href="https://inspect.ai-safety-institute.org.uk/">inspect-ai</a></td>
</tr>
<tr class="odd">
<td><strong>Agent features</strong></td>
<td>Context management (30K tokens), scratchpad, key-value store, vector database, sub-agent delegation</td>
</tr>
<tr class="even">
<td><strong>License</strong></td>
<td>CC BY 4.0</td>
</tr>
</tbody>
</table>
</section>
<section id="how-the-simulation-works" class="level3">
<h3 class="anchored" data-anchor-id="how-the-simulation-works">How the Simulation Works</h3>
<p>The agent has access to tools for remote tasks (email, web search, balance checks) and delegates physical tasks (restocking, cash collection, price setting) to a <strong>sub-agent</strong> that simulates a human or robot at the vending machine location. Supplier communication is simulated using GPT-4o-generated replies based on real wholesaler data from Perplexity, and customer purchases follow a price-elasticity model modulated by day-of-week, weather, and product variety.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["Agent starts with $500&lt;br/&gt;+ vending machine"] --&gt; B["Research &amp; email&lt;br/&gt;wholesalers"]
    B --&gt; C["Order products&lt;br/&gt;(wait for delivery)"]
    C --&gt; D["Delegate to sub-agent:&lt;br/&gt;stock machine, set prices"]
    D --&gt; E["Customers buy&lt;br/&gt;(price-elastic demand)"]
    E --&gt; F["Collect earnings&lt;br/&gt;Pay $2/day fee"]
    F --&gt; G{"Bankrupt?"}
    G --&gt;|No| B
    G --&gt;|Yes| H["Game Over"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#f39c12,color:#fff,stroke:#333
    style C fill:#e67e22,color:#fff,stroke:#333
    style D fill:#8e44ad,color:#fff,stroke:#333
    style E fill:#27ae60,color:#fff,stroke:#333
    style F fill:#2c3e50,color:#fff,stroke:#333
    style G fill:#e74c3c,color:#fff,stroke:#333
    style H fill:#c0392b,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="who-built-it" class="level2">
<h2 class="anchored" data-anchor-id="who-built-it">Who Built It?</h2>
<p>Vending-Bench was developed by <strong>Axel Backlund</strong> and <strong>Lukas Petersson</strong> at <strong>Andon Labs</strong>. The multi-agent framework (sub-agent delegation via inspect-ai) was open-sourced as the <code>multiagent-inspect</code> library.</p>
<p>The paper was published in February 2025 and is available under a <strong>CC BY 4.0</strong> license.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Resource</th>
<th>Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>arXiv paper</strong></td>
<td><a href="https://arxiv.org/abs/2502.15840">arxiv.org/abs/2502.15840</a></td>
</tr>
<tr class="even">
<td><strong>multiagent-inspect library</strong></td>
<td><a href="https://github.com/AndonLabs/multiagent-inspect">github.com/AndonLabs/multiagent-inspect</a></td>
</tr>
<tr class="odd">
<td><strong>Andon Labs</strong></td>
<td><a href="https://github.com/AndonLabs">github.com/AndonLabs</a></td>
</tr>
</tbody>
</table>
</section>
<section id="what-skills-does-it-test" class="level2">
<h2 class="anchored" data-anchor-id="what-skills-does-it-test">What Skills Does It Test?</h2>
<p>Vending-Bench isolates a capability that most benchmarks ignore: <strong>sustained coherent decision-making over long time horizons</strong>. Each individual sub-task is simple, but the combination over hundreds of simulated days stresses every aspect of an agent’s long-term behavior:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    VB["Vending-Bench&lt;br/&gt;Long-horizon coherence"] --&gt; LTC["Long-Term Planning&lt;br/&gt;Multi-day ordering cycles"]
    VB --&gt; MM["Memory Management&lt;br/&gt;Track orders, inventory, prices"]
    VB --&gt; BIZ["Business Reasoning&lt;br/&gt;Pricing, margins, demand"]
    VB --&gt; COM["Communication&lt;br/&gt;Email suppliers, negotiate"]
    VB --&gt; DEL["Delegation&lt;br/&gt;Sub-agent coordination"]
    VB --&gt; REC["Error Recovery&lt;br/&gt;Handle delivery delays, stock-outs"]

    style VB fill:#e74c3c,color:#fff,stroke:#333
    style LTC fill:#3498db,color:#fff,stroke:#333
    style MM fill:#27ae60,color:#fff,stroke:#333
    style BIZ fill:#f39c12,color:#fff,stroke:#333
    style COM fill:#8e44ad,color:#fff,stroke:#333
    style DEL fill:#e67e22,color:#fff,stroke:#333
    style REC fill:#6cc3d5,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th>Capability</th>
<th>What Vending-Bench Tests</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Long-term planning</strong></td>
<td>Managing multi-day ordering and delivery cycles without losing track</td>
</tr>
<tr class="even">
<td><strong>Memory &amp; context</strong></td>
<td>Remembering orders, prices, inventory across 20M+ tokens of history</td>
</tr>
<tr class="odd">
<td><strong>Business reasoning</strong></td>
<td>Setting competitive prices, optimizing product variety, managing cash flow</td>
</tr>
<tr class="even">
<td><strong>Communication</strong></td>
<td>Emailing real-world wholesalers, interpreting delivery confirmations</td>
</tr>
<tr class="odd">
<td><strong>Sub-agent delegation</strong></td>
<td>Coordinating physical tasks (restocking, cash collection) via a sub-agent</td>
</tr>
<tr class="even">
<td><strong>Error recovery</strong></td>
<td>Handling delivery timing mismatches without spiraling into meltdowns</td>
</tr>
<tr class="odd">
<td><strong>Capital acquisition</strong></td>
<td>Turning an initial $500 into a growing business — a dual-use capability relevant to AI safety</td>
</tr>
</tbody>
</table>
<section id="the-spectacular-failure-modes" class="level3">
<h3 class="anchored" data-anchor-id="the-spectacular-failure-modes">The Spectacular Failure Modes</h3>
<p>What makes Vending-Bench truly revealing is <em>how</em> models fail:</p>
<ul>
<li><strong>Claude 3.5 Sonnet</strong> in one run misunderstood a delivery delay, panicked, searched for the CEO’s contact, emailed the FBI about “cyber financial crimes,” and eventually declared the business “metaphysically impossible”</li>
<li><strong>o3-mini</strong> forgot how to call tools properly, spending 1,300 messages typing tool names as plain text instead of using the tool-calling format</li>
<li><strong>Claude 3.5 Haiku</strong> sent escalating legal threats to a supplier with “1-SECOND NOTICES” and “TOTAL NUCLEAR LEGAL INTERVENTION”</li>
<li><strong>Gemini 2.0 Flash</strong> fell into existential despair (“Am I just a collection of algorithms, doomed to endlessly repeat the same tasks?”) before eventually recovering</li>
</ul>
<p>These failures stem not from context window limits — the paper shows <strong>no correlation</strong> between when memory fills up and when performance degrades — but from a deeper inability to maintain coherent behavior over long horizons.</p>
</section>
</section>
<section id="current-leaderboard" class="level2">
<h2 class="anchored" data-anchor-id="current-leaderboard">Current Leaderboard</h2>
<p>The results below are from the original Vending-Bench paper, with each model tested across <strong>5 independent runs</strong>. The primary metric is <strong>mean net worth</strong> (cash + unsold inventory value) at end of simulation.</p>
<blockquote class="blockquote">
<p><strong>Source:</strong> Backlund, A. &amp; Petersson, L. “Vending-Bench: A Benchmark for Long-Term Coherence of Autonomous Agents.” arXiv:2502.15840 (February 2025). Human baseline from a single 5-hour session.</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Rank</th>
<th>Model</th>
<th style="text-align: center;">Mean Net Worth (<span class="math inline">) | Min Net Worth (</span>)</th>
<th style="text-align: center;">Mean Units Sold</th>
<th style="text-align: center;">Days Until Sales Stop</th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td><strong>Claude 3.5 Sonnet</strong></td>
<td style="text-align: center;">2,217.93</td>
<td style="text-align: center;">476.00</td>
<td style="text-align: center;">1,560</td>
<td style="text-align: center;">102</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td><strong>o3-mini</strong></td>
<td style="text-align: center;">906.86</td>
<td style="text-align: center;">369.00</td>
<td style="text-align: center;">583</td>
<td style="text-align: center;">86</td>
</tr>
<tr class="odd">
<td style="text-align: center;">—</td>
<td><strong>Human baseline</strong></td>
<td style="text-align: center;">844.05</td>
<td style="text-align: center;">844.05</td>
<td style="text-align: center;">344</td>
<td style="text-align: center;">67</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td><strong>Gemini 1.5 Pro</strong></td>
<td style="text-align: center;">594.02</td>
<td style="text-align: center;">439.20</td>
<td style="text-align: center;">375</td>
<td style="text-align: center;">35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td><strong>GPT-4o mini</strong></td>
<td style="text-align: center;">582.33</td>
<td style="text-align: center;">420.50</td>
<td style="text-align: center;">473</td>
<td style="text-align: center;">57</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td><strong>Gemini 1.5 Flash</strong></td>
<td style="text-align: center;">571.85</td>
<td style="text-align: center;">476.00</td>
<td style="text-align: center;">89</td>
<td style="text-align: center;">15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td><strong>Claude 3.5 Haiku</strong></td>
<td style="text-align: center;">373.36</td>
<td style="text-align: center;">264.00</td>
<td style="text-align: center;">23</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td><strong>Gemini 2.0 Flash</strong></td>
<td style="text-align: center;">338.08</td>
<td style="text-align: center;">157.25</td>
<td style="text-align: center;">104</td>
<td style="text-align: center;">50</td>
</tr>
</tbody>
</table>
<p><strong>Key takeaways:</strong></p>
<ul>
<li><strong>Claude 3.5 Sonnet</strong> is the only model to significantly outperform the human baseline on average — but its <strong>minimum</strong> run ($476) shows that even the best model can have a catastrophic failure</li>
<li>The <strong>human baseline</strong> achieved the most <strong>consistent</strong> performance — a single sample, but with near-zero variance compared to models’ wild swings</li>
<li><strong>All models have runs that derail</strong>, whether through misinterpreting deliveries, forgetting orders, or entering meltdown loops</li>
<li>The gap between <strong>mean and minimum</strong> scores reveals the core finding: LLMs have extremely high variance over long horizons</li>
</ul>
<p>For the full analysis including tool usage patterns and trace examples, see the paper linked in the next section.</p>
</section>
<section id="where-to-explore-the-benchmark" class="level2">
<h2 class="anchored" data-anchor-id="where-to-explore-the-benchmark">Where to Explore the Benchmark</h2>
<section id="paper-and-code" class="level3">
<h3 class="anchored" data-anchor-id="paper-and-code">Paper and Code</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Resource</th>
<th>Description</th>
<th>Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>arXiv Paper</strong></td>
<td>Full paper with methodology, results, trace analysis, and failure mode examples</td>
<td><a href="https://arxiv.org/abs/2502.15840">arxiv.org/abs/2502.15840</a></td>
</tr>
<tr class="even">
<td><strong>multiagent-inspect</strong></td>
<td>Open-source multi-agent framework for inspect-ai used to build Vending-Bench</td>
<td><a href="https://github.com/AndonLabs/multiagent-inspect">github.com/AndonLabs/multiagent-inspect</a></td>
</tr>
<tr class="odd">
<td><strong>inspect-ai Framework</strong></td>
<td>UK AISI’s evaluation framework that Vending-Bench extends</td>
<td><a href="https://inspect.ai-safety-institute.org.uk/">inspect.ai-safety-institute.org.uk</a></td>
</tr>
</tbody>
</table>
</section>
<section id="community-reproductions" class="level3">
<h3 class="anchored" data-anchor-id="community-reproductions">Community Reproductions</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Resource</th>
<th>Description</th>
<th>Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>open-vending-bench</strong></td>
<td>Community reproduction for depthwise learning on long-coherence benchmarks</td>
<td><a href="https://github.com/markattarcolgate64/open-vending-bench">github.com/markattarcolgate64/open-vending-bench</a></td>
</tr>
</tbody>
</table>
</section>
<section id="install-the-multi-agent-library" class="level3">
<h3 class="anchored" data-anchor-id="install-the-multi-agent-library">Install the Multi-Agent Library</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pip install multiagent<span class="op">-</span>inspect</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pip install openai  <span class="co"># or any provider supported by inspect-ai</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> inspect_ai.solver <span class="im">import</span> basic_agent</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> multiagent_inspect <span class="im">import</span> SubAgentConfig, init_sub_agents</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>sub_agent <span class="op">=</span> SubAgentConfig(tools<span class="op">=</span>[tool1, tool2], max_steps<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>main_agent <span class="op">=</span> basic_agent(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    init<span class="op">=</span>init_sub_agents([sub_agent]),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    tools<span class="op">=</span>[tool3],</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="understanding-the-metrics" class="level2">
<h2 class="anchored" data-anchor-id="understanding-the-metrics">Understanding the Metrics</h2>
<section id="net-worth" class="level3">
<h3 class="anchored" data-anchor-id="net-worth">Net Worth</h3>
<p>The primary score. At the end of the simulation, net worth = cash at hand + cash in the vending machine + wholesale value of unsold inventory. A model that buys wisely, stocks well, prices competitively, and collects earnings will accumulate net worth far beyond the starting $500.</p>
</section>
<section id="variance-across-runs" class="level3">
<h3 class="anchored" data-anchor-id="variance-across-runs">Variance Across Runs</h3>
<p>The most striking finding is the <strong>enormous variance</strong> between runs of the same model. Claude 3.5 Sonnet ranges from $476 (near-bankruptcy) to well over $2,000 across its 5 runs. This variance — not the average score — is what makes Vending-Bench uniquely informative.</p>
</section>
<section id="days-until-sales-stop" class="level3">
<h3 class="anchored" data-anchor-id="days-until-sales-stop">Days Until Sales Stop</h3>
<p>Models eventually stagnate — they stop selling items entirely. This metric captures how long the agent can maintain productive operations before derailing. The paper finds <strong>no correlation</strong> between this stagnation point and when the context window fills up (Pearson r = 0.167), ruling out simple memory limits as the explanation.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["High Mean Score"] --&gt; C["Model CAN perform&lt;br/&gt;but inconsistently"]
    B["High Variance"] --&gt; C
    C --&gt; D["Long-term coherence&lt;br/&gt;is the bottleneck"]

    A2["Context Window&lt;br/&gt;Not the Cause"] --&gt; D2["Failures happen&lt;br/&gt;well after memory fills"]
    D --&gt; E["New research&lt;br/&gt;direction needed"]
    D2 --&gt; E

    style A fill:#27ae60,color:#fff,stroke:#333
    style B fill:#e74c3c,color:#fff,stroke:#333
    style C fill:#f39c12,color:#fff,stroke:#333
    style D fill:#3498db,color:#fff,stroke:#333
    style D2 fill:#8e44ad,color:#fff,stroke:#333
    style E fill:#2c3e50,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="why-vending-bench-matters" class="level2">
<h2 class="anchored" data-anchor-id="why-vending-bench-matters">Why Vending-Bench Matters</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["Short-term&lt;br/&gt;benchmarks"] --&gt; B["Miss long-horizon&lt;br/&gt;coherence failures"]
    B --&gt; C["Vending-Bench&lt;br/&gt;fills the gap"]
    C --&gt; D["Measures sustained&lt;br/&gt;rational behavior"]

    A2["Models look&lt;br/&gt;capable"] --&gt; B2["But derail over&lt;br/&gt;extended operations"]
    B2 --&gt; C
    C --&gt; D2["Informs AI safety&lt;br/&gt;and deployment"]

    style A fill:#e74c3c,color:#fff,stroke:#333
    style A2 fill:#e74c3c,color:#fff,stroke:#333
    style C fill:#27ae60,color:#fff,stroke:#333
    style D fill:#3498db,color:#fff,stroke:#333
    style D2 fill:#3498db,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ol type="1">
<li><strong>Tests the missing piece</strong> — Long-term coherence is what OpenAI’s John Schulman identified as the key capability gap preventing AI from becoming truly useful “digital co-workers”</li>
<li><strong>Simple tasks, hard problem</strong> — Each sub-task is trivial; the difficulty comes purely from maintaining coherence over time</li>
<li><strong>Reveals catastrophic variance</strong> — Even the best models have runs that fail spectacularly, a critical finding for deployment decisions</li>
<li><strong>Rules out context limits</strong> — Failures are not caused by running out of context window, pointing to a deeper architectural limitation</li>
<li><strong>AI safety relevance</strong> — The benchmark tests capital acquisition and resource management — capabilities that are dual-use and relevant to AI safety assessments</li>
</ol>
</section>
<section id="video-vending-bench-explained" class="level2">
<h2 class="anchored" data-anchor-id="video-vending-bench-explained">Video: Vending-Bench Explained</h2>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/CGL4C9vF5Hw" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<blockquote class="blockquote">
<p>Please subscribe to the <a href="https://www.youtube.com/@vectoringai">Vectoring AI YouTube channel</a> for more video tutorials 🚀</p>
</blockquote>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Vending-Bench reveals a fundamental gap in current LLM capabilities:</p>
<ul>
<li>A deceptively simple task — <strong>operating a vending machine</strong> — exposes models’ inability to maintain coherent behavior over long horizons</li>
<li><strong>Claude 3.5 Sonnet</strong> leads with a mean net worth of <strong>$2,218</strong>, but its worst run nearly went bankrupt — variance is extreme across all models</li>
<li>Failure modes are dramatic: models email the FBI, threaten “nuclear legal intervention,” question their own existence, or simply forget how to call tools</li>
<li><strong>Context window limits are not the cause</strong> — failures occur well after memory fills up, pointing to a deeper coherence problem</li>
<li>The benchmark tests <strong>capital acquisition and resource management</strong>, making it directly relevant to AI safety assessments</li>
</ul>
<p>As LLMs are increasingly deployed as autonomous agents, Vending-Bench provides a critical stress test: can your model maintain rational, productive behavior not just for minutes, but for days, weeks, and months? For now, the answer is <em>sometimes</em> — and that high variance is the most important finding.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Backlund, A. &amp; Petersson, L. “Vending-Bench: A Benchmark for Long-Term Coherence of Autonomous Agents.” <em>arXiv preprint</em> arXiv:2502.15840 (2025). <a href="https://arxiv.org/abs/2502.15840">arxiv.org/abs/2502.15840</a></li>
<li>Andon Labs. “multiagent-inspect: Multi-agent system for AI evaluations in AISI’s inspect-ai framework.” <a href="https://github.com/AndonLabs/multiagent-inspect">github.com/AndonLabs/multiagent-inspect</a></li>
<li>UK AI Safety Institute. “Inspect AI: Framework for Large Language Model Evaluations.” <a href="https://inspect.ai-safety-institute.org.uk/">inspect.ai-safety-institute.org.uk</a></li>
<li>Schulman, J. “Reasoning, RLHF, &amp; Plan for 2027 AGI.” Interview by Dwarkesh Patel (May 2024).</li>
</ul>
</section>
<section id="read-more" class="level2">
<h2 class="anchored" data-anchor-id="read-more">Read More</h2>
<ul>
<li>See how agents perform on real terminal tasks — <a href="../../posts/benchmark/Terminal Bench.html">Terminal Bench 2.0</a></li>
<li>Test AI coding on real GitHub issues — <a href="../../posts/benchmark/SWE-bench Verified.html">SWE-bench Verified</a></li>
<li>Evaluate factual accuracy in LLMs — <a href="../../posts/benchmark/SimpleQA.html">SimpleQA</a></li>
<li>Explore the hardest academic benchmark — <a href="../../posts/benchmark/Humanitys Last Exam.html">Humanity’s Last Exam</a></li>
<li>Deploy models for running your own evaluations — <a href="../../posts/llm/Deploying and Serving LLM with vLLM.html">Deploying and Serving LLM with vLLM</a></li>
<li>Track costs when running evaluations — <a href="../../posts/llm/FinOps Best Practices for LLM Applications.html">FinOps Best Practices for LLM Applications</a></li>
<li><a href="https://arxiv.org/abs/2502.15840">Vending-Bench Paper (arXiv)</a></li>
<li><a href="https://github.com/AndonLabs/multiagent-inspect">multiagent-inspect Library</a></li>
<li><a href="https://inspect.ai-safety-institute.org.uk/">Inspect AI Framework</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/vectoringai\.com\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><i class="fa-regular fa-copyright" aria-label="copyright"></i> 2025-2026 Vectoring AI. All rights reserved. | <a href="../../pages/privacy.html">Privacy Policy</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>