<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vectoring AI">
<meta name="dcterms.date" content="2025-09-23">
<meta name="keywords" content="AI history, 2010s AI, deep learning, AlexNet, ImageNet, Geoffrey Hinton, Alex Krizhevsky, Ilya Sutskever, convolutional neural networks, IBM Watson, Siri, Word2Vec, generative adversarial networks, GANs, Ian Goodfellow, AlphaGo, DeepMind, Lee Sedol, reinforcement learning, transformer, attention is all you need, self-attention, BERT, GPT, OpenAI, large language models, ResNet, DeepDream, Alexa, DeepFace, Deep Q-Network, AlphaGo Zero, AlphaZero, AlphaStar, GPT-2, GPT-3, Waymo, autonomous driving, AI ethics, NeurIPS, Google Brain, Facebook AI Research, neural style transfer, few-shot learning">
<meta name="description" content="Deep Learning Revolution, Transformers, and the Rise of Modern AI — how convolutional networks, reinforcement learning, and attention mechanisms reshaped the world">

<title>2010s AI Milestones – Vectoring AI</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../..//images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dbc92dda8186f57fa2e333fbb71d6a9d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-23f3439e4bd86aeeff5ff0174c43dd13.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-Q4RQ337R0F"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-Q4RQ337R0F', { 'anonymize_ip': true});
</script>
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9738638303661485" crossorigin="anonymous"></script>
<!-- Cookie Consent Banner (GDPR compliant) -->
<style>
#cookie-consent-banner {
  display: none;
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #1d1d1d !important;
  color: #ffffff !important;
  padding: 16px 24px;
  z-index: 9999;
  font-size: 14px;
  box-shadow: 0 -2px 10px rgba(0,0,0,0.3);
}
#cookie-consent-banner p {
  margin: 0 0 12px 0;
  line-height: 1.5;
  color: #ffffff !important;
}
#cookie-consent-banner a {
  color: #78b9ff;
  text-decoration: underline;
}
#cookie-consent-buttons {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}
#cookie-consent-buttons button {
  padding: 8px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: 600;
}
#btn-accept-all {
  background: #3B70FE;
  color: #fff;
}
#btn-accept-essential {
  background: #555;
  color: #fff;
}
#btn-deny {
  background: transparent;
  color: #ccc;
  border: 1px solid #666 !important;
}
</style>

<meta property="og:title" content="2010s AI Milestones – Vectoring AI">
<meta property="og:description" content="Deep Learning Revolution, Transformers, and the Rise of Modern AI — how convolutional networks, reinforcement learning, and attention mechanisms reshaped the world">
<meta property="og:image" content="https://vectoringai.com/images/milestone/2010s-ai-milestones-300px.png">
<meta property="og:site_name" content="Vectoring AI">
<meta property="og:image:height" content="200">
<meta property="og:image:width" content="300">
<meta name="twitter:title" content="2010s AI Milestones – Vectoring AI">
<meta name="twitter:description" content="Deep Learning Revolution, Transformers, and the Rise of Modern AI — how convolutional networks, reinforcement learning, and attention mechanisms reshaped the world">
<meta name="twitter:image" content="https://vectoringai.com/images/milestone/2010s-ai-milestones-300px.png">
<meta name="twitter:image-height" content="200">
<meta name="twitter:image-width" content="300">
<meta name="twitter:card" content="summary_large_image">
</head><body class="nav-sidebar docked quarto-light"><div id="cookie-consent-banner">
  <p>We use cookies to serve personalized ads (Google AdSense) and analyze traffic.
    You can accept all cookies, accept only essential cookies, or deny non-essential cookies.
    <a href="../../pages/privacy.html">Privacy Policy</a>
  </p>
  <div id="cookie-consent-buttons">
    <button id="btn-accept-all">Accept All</button>
    <button id="btn-accept-essential">Essential Only</button>
    <button id="btn-deny">Deny</button>
  </div>
</div>

<script>
(function() {
  var consent = localStorage.getItem("cookie_consent");

  function loadAdSense() {
    if (document.querySelector('script[src*="adsbygoogle"]')) return;
    var s = document.createElement("script");
    s.async = true;
    s.src = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9738638303661485";
    s.crossOrigin = "anonymous";
    document.head.appendChild(s);
  }

  function showBanner() {
    document.getElementById("cookie-consent-banner").style.display = "block";
  }

  function hideBanner() {
    document.getElementById("cookie-consent-banner").style.display = "none";
  }

  if (consent === "all") {
    loadAdSense();
  } else if (consent === "essential" || consent === "denied") {
    // Do not load AdSense
  } else {
    // No choice made yet — show banner, do not load AdSense
    window.addEventListener("DOMContentLoaded", showBanner);
  }

  window.addEventListener("DOMContentLoaded", function() {
    document.getElementById("btn-accept-all").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "all");
      hideBanner();
      loadAdSense();
    });
    document.getElementById("btn-accept-essential").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "essential");
      hideBanner();
    });
    document.getElementById("btn-deny").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "denied");
      hideBanner();
    });
  });
})();
</script>
<script>
// Inject missing Open Graph tags that Facebook requires for proper link sharing
(function () {
  if (!document.querySelector('meta[property="og:url"]')) {
    var m = document.createElement("meta");
    m.setAttribute("property", "og:url");
    m.setAttribute("content", window.location.href);
    document.head.appendChild(m);
  }
  if (!document.querySelector('meta[property="og:type"]')) {
    var t = document.createElement("meta");
    t.setAttribute("property", "og:type");
    t.setAttribute("content", "article");
    document.head.appendChild(t);
  }
  // Fix double-slash in og:image (site-url trailing slash + /images/...)
  var ogImg = document.querySelector('meta[property="og:image"]');
  if (ogImg) {
    ogImg.setAttribute("content", ogImg.getAttribute("content").replace(/([^:])\/\//g, "$1/"));
  }
  var twImg = document.querySelector('meta[name="twitter:image"]');
  if (twImg) {
    twImg.setAttribute("content", twImg.getAttribute("content").replace(/([^:])\/\//g, "$1/"));
  }
})();
</script>
<style>
.share-widget {
  display: flex;
  align-items: center;
  gap: 0.7rem;
  margin: 0.8rem 0 1.2rem 0;
  padding: 0.5rem 0;
}
.share-widget .share-icon {
  width: 20px;
  height: 20px;
  fill: #555;
}
.share-widget .share-label {
  font-size: 0.82rem;
  font-weight: 600;
  color: #555;
}
.share-widget .share-divider {
  width: 1px;
  height: 22px;
  background: #ddd;
}
.share-widget a {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  transition: transform 0.2s, box-shadow 0.2s;
  text-decoration: none !important;
}
.share-widget a:hover {
  transform: scale(1.15);
  box-shadow: 0 2px 8px rgba(0,0,0,0.15);
}
.share-widget a svg {
  width: 20px;
  height: 20px;
}
.notebook-widget {
  margin: 0 0 1rem 0;
}
.notebook-widget a {
  display: inline-block;
  transition: transform 0.2s;
}
.notebook-widget a:hover {
  transform: scale(1.05);
}
</style>
<script>
document.addEventListener("DOMContentLoaded", function () {
  if (!window.location.pathname.includes("/posts/")) return;

  var rawTitle = document.title;
  var rawUrl = window.location.href;
  var title = encodeURIComponent(rawTitle);
  var url = encodeURIComponent(rawUrl);

  var widget = document.createElement("div");
  widget.className = "share-widget";
  widget.innerHTML =
    '<svg class="share-icon" viewBox="0 0 24 24"><path d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92s2.92-1.31 2.92-2.92-1.31-2.92-2.92-2.92z"/></svg>' +
    '<span class="share-label">Share</span>' +
    '<div class="share-divider"></div>' +
    '<a href="https://twitter.com/intent/tweet?text=' + title + '&url=' + url + '" target="_blank" rel="noopener" title="Share on X"><svg viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg></a>' +
    '<a href="https://www.facebook.com/sharer/sharer.php?u=' + url + '" target="_blank" rel="noopener" title="Share on Facebook"><svg viewBox="0 0 24 24" fill="#1877F2"><path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/></svg></a>' +
    '<a href="https://www.linkedin.com/shareArticle?mini=true&url=' + url + '&title=' + title + '" target="_blank" rel="noopener" title="Share on LinkedIn"><svg viewBox="0 0 24 24" fill="#0A66C2"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg></a>';

  // Desktop: open a centered popup (standard share UX).
  // Mobile: let the default target="_blank" navigate so the OS can
  //         route to the native app (Facebook, LinkedIn, etc.).
  var isMobile = /Android|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i.test(navigator.userAgent);
  if (!isMobile) {
    widget.querySelectorAll("a").forEach(function (a) {
      a.addEventListener("click", function (e) {
        e.preventDefault();
        var w = 600, h = 500;
        var left = (screen.width - w) / 2;
        var top = (screen.height - h) / 2;
        window.open(
          this.href, "share",
          "width=" + w + ",height=" + h + ",left=" + left + ",top=" + top + ",noopener,noreferrer"
        );
      });
    });
  }

  // Insert right after the title-block header, before Keywords
  var header = document.querySelector("header#title-block-header");
  if (header && header.nextSibling) {
    header.parentNode.insertBefore(widget, header.nextSibling);
  }

  // Add Colab / notebook button if the page has a notebook-link element
  var nbEl = document.getElementById("notebook-link");
  if (nbEl && nbEl.dataset.url) {
    var nbWidget = document.createElement("div");
    nbWidget.className = "notebook-widget";
    nbWidget.innerHTML =
      '<a href="' + nbEl.dataset.url + '" target="_blank" rel="noopener" title="Open notebook in Google Colab">' +
      '<img src="/images/colab.png" alt="Open in Colab" style="height:28px">' +
      '</a>';
    // Insert right after the share widget
    if (widget.nextSibling) {
      widget.parentNode.insertBefore(nbWidget, widget.nextSibling);
    } else if (widget.parentNode) {
      widget.parentNode.appendChild(nbWidget);
    }
  }
});
</script>
<script>

  var link = document.createElement('link');

  link.rel = 'canonical';

  var path = window.location.pathname.replace(/index\.html$/, '');

  link.href = 'https://vectoringai.com' + path;

  document.head.appendChild(link);

</script>

<script>

document.addEventListener('DOMContentLoaded', function() {

  var ogTitle = document.querySelector('meta[property="og:title"]');

  var ogDesc = document.querySelector('meta[property="og:description"]');

  var ogImage = document.querySelector('meta[property="og:image"]');

  var dcDate = document.querySelector('meta[name="dcterms.date"]');



  if (!ogTitle) return;



  var isArticle = !!dcDate;

  var jsonld = {

    "@context": "https://schema.org",

    "@type": isArticle ? "Article" : "WebPage",

    "headline": ogTitle.content.replace(/ – Vectoring AI$/, ''),

    "description": ogDesc ? ogDesc.content : "",

    "url": window.location.href,

    "author": {

      "@type": "Organization",

      "name": "Vectoring AI",

      "url": "https://vectoringai.com/pages/about.html"

    },

    "publisher": {

      "@type": "Organization",

      "name": "Vectoring AI",

      "url": "https://vectoringai.com",

      "logo": {

        "@type": "ImageObject",

        "url": "https://vectoringai.com/images/favicon_io/android-chrome-512x512.png"

      }

    }

  };



  if (ogImage) jsonld.image = ogImage.content;

  if (dcDate) jsonld.datePublished = dcDate.content;



  var el = document.createElement('script');

  el.type = 'application/ld+json';

  el.textContent = JSON.stringify(jsonld);

  document.head.appendChild(el);

});

</script>

<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Vectoring AI
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Vectoring AI</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/VectoringAI" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.youtube.com/@vectoringai" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-youtube"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">AI Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLMs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/agent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Agents</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/rag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RAG</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/benchmark.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Benchmarks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/milestone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Milestones</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title"><strong>Sections</strong></h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#timeline-of-key-milestones" id="toc-timeline-of-key-milestones" class="nav-link" data-scroll-target="#timeline-of-key-milestones">Timeline of Key Milestones</a></li>
  <li><a href="#ibm-watson-defeats-jeopardy-champions-2011" id="toc-ibm-watson-defeats-jeopardy-champions-2011" class="nav-link" data-scroll-target="#ibm-watson-defeats-jeopardy-champions-2011">IBM Watson Defeats Jeopardy! Champions (2011)</a></li>
  <li><a href="#siri-and-the-rise-of-voice-assistants-2011" id="toc-siri-and-the-rise-of-voice-assistants-2011" class="nav-link" data-scroll-target="#siri-and-the-rise-of-voice-assistants-2011">Siri and the Rise of Voice Assistants (2011)</a></li>
  <li><a href="#alexnet-the-imagenet-breakthrough-2012" id="toc-alexnet-the-imagenet-breakthrough-2012" class="nav-link" data-scroll-target="#alexnet-the-imagenet-breakthrough-2012">AlexNet: The ImageNet Breakthrough (2012)</a></li>
  <li><a href="#word2vec-learning-the-semantics-of-language-2013" id="toc-word2vec-learning-the-semantics-of-language-2013" class="nav-link" data-scroll-target="#word2vec-learning-the-semantics-of-language-2013">Word2Vec: Learning the Semantics of Language (2013)</a></li>
  <li><a href="#deep-q-network-reinforcement-learning-from-pixels-20132015" id="toc-deep-q-network-reinforcement-learning-from-pixels-20132015" class="nav-link" data-scroll-target="#deep-q-network-reinforcement-learning-from-pixels-20132015">Deep Q-Network: Reinforcement Learning from Pixels (2013–2015)</a></li>
  <li><a href="#generative-adversarial-networks-the-art-of-ai-creation-2014" id="toc-generative-adversarial-networks-the-art-of-ai-creation-2014" class="nav-link" data-scroll-target="#generative-adversarial-networks-the-art-of-ai-creation-2014">Generative Adversarial Networks: The Art of AI Creation (2014)</a></li>
  <li><a href="#resnet-the-power-of-depth-2015" id="toc-resnet-the-power-of-depth-2015" class="nav-link" data-scroll-target="#resnet-the-power-of-depth-2015">ResNet: The Power of Depth (2015)</a></li>
  <li><a href="#alphago-ai-conquers-the-ancient-game-of-go-2016" id="toc-alphago-ai-conquers-the-ancient-game-of-go-2016" class="nav-link" data-scroll-target="#alphago-ai-conquers-the-ancient-game-of-go-2016">AlphaGo: AI Conquers the Ancient Game of Go (2016)</a></li>
  <li><a href="#alphago-zero-and-alphazero-learning-from-scratch-2017" id="toc-alphago-zero-and-alphazero-learning-from-scratch-2017" class="nav-link" data-scroll-target="#alphago-zero-and-alphazero-learning-from-scratch-2017">AlphaGo Zero and AlphaZero: Learning from Scratch (2017)</a></li>
  <li><a href="#the-transformer-attention-is-all-you-need-2017" id="toc-the-transformer-attention-is-all-you-need-2017" class="nav-link" data-scroll-target="#the-transformer-attention-is-all-you-need-2017">The Transformer: Attention Is All You Need (2017)</a></li>
  <li><a href="#bert-bidirectional-pretrained-language-understanding-2018" id="toc-bert-bidirectional-pretrained-language-understanding-2018" class="nav-link" data-scroll-target="#bert-bidirectional-pretrained-language-understanding-2018">BERT: Bidirectional Pretrained Language Understanding (2018)</a></li>
  <li><a href="#the-gpt-series-from-117-million-to-175-billion-parameters-20182020" id="toc-the-gpt-series-from-117-million-to-175-billion-parameters-20182020" class="nav-link" data-scroll-target="#the-gpt-series-from-117-million-to-175-billion-parameters-20182020">The GPT Series: From 117 Million to 175 Billion Parameters (2018–2020)</a></li>
  <li><a href="#alphastar-mastering-real-time-strategy-2019" id="toc-alphastar-mastering-real-time-strategy-2019" class="nav-link" data-scroll-target="#alphastar-mastering-real-time-strategy-2019">AlphaStar: Mastering Real-Time Strategy (2019)</a></li>
  <li><a href="#waymo-and-the-road-to-autonomous-driving-20182020" id="toc-waymo-and-the-road-to-autonomous-driving-20182020" class="nav-link" data-scroll-target="#waymo-and-the-road-to-autonomous-driving-20182020">Waymo and the Road to Autonomous Driving (2018–2020)</a></li>
  <li><a href="#consumer-ai-and-the-invisible-revolution-2010s" id="toc-consumer-ai-and-the-invisible-revolution-2010s" class="nav-link" data-scroll-target="#consumer-ai-and-the-invisible-revolution-2010s">Consumer AI and the Invisible Revolution (2010s)</a></li>
  <li><a href="#ai-ethics-the-reckoning-2010s2020" id="toc-ai-ethics-the-reckoning-2010s2020" class="nav-link" data-scroll-target="#ai-ethics-the-reckoning-2010s2020">AI Ethics: The Reckoning (2010s–2020)</a></li>
  <li><a href="#anatomy-of-the-deep-learning-revolution" id="toc-anatomy-of-the-deep-learning-revolution" class="nav-link" data-scroll-target="#anatomy-of-the-deep-learning-revolution">Anatomy of the Deep Learning Revolution</a></li>
  <li><a href="#video-2010s-ai-milestones-deep-learning-revolution-and-modern-ai" id="toc-video-2010s-ai-milestones-deep-learning-revolution-and-modern-ai" class="nav-link" data-scroll-target="#video-2010s-ai-milestones-deep-learning-revolution-and-modern-ai">Video: 2010s AI Milestones — Deep Learning Revolution and Modern AI</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#read-more" id="toc-read-more" class="nav-link" data-scroll-target="#read-more">Read More</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2010s AI Milestones</h1>
</div>

<div>
  <div class="description">
    Deep Learning Revolution, Transformers, and the Rise of Modern AI — how convolutional networks, reinforcement learning, and attention mechanisms reshaped the world
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><a href="https://vectoringai.com/pages/about.html">Vectoring AI</a> </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 23, 2025</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>AI history, 2010s AI, deep learning, AlexNet, ImageNet, Geoffrey Hinton, Alex Krizhevsky, Ilya Sutskever, convolutional neural networks, IBM Watson, Siri, Word2Vec, generative adversarial networks, GANs, Ian Goodfellow, AlphaGo, DeepMind, Lee Sedol, reinforcement learning, transformer, attention is all you need, self-attention, BERT, GPT, OpenAI, large language models, ResNet, DeepDream, Alexa, DeepFace, Deep Q-Network, AlphaGo Zero, AlphaZero, AlphaStar, GPT-2, GPT-3, Waymo, autonomous driving, AI ethics, NeurIPS, Google Brain, Facebook AI Research, neural style transfer, few-shot learning</p>
  </div>
</div>

</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../..\images/milestone/2010s-ai-milestones-300px.png" class="img-fluid figure-img" width="300"></p>
<figcaption>2010s AI milestones: deep learning revolution and transformers</figcaption>
</figure>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The 2010s were the decade that <strong>deep learning conquered the world</strong>. What had been a niche research direction — training neural networks with many layers — erupted into a technological revolution that reshaped industries, captivated the public imagination, and raised profound questions about the future of human intelligence.</p>
<p>The decade began with a dramatic signal: in 2012, <strong>AlexNet</strong> crushed the ImageNet competition by a margin so wide it stunned the computer vision community, proving that deep convolutional networks trained on GPUs could outperform decades of hand-crafted feature engineering. Within two years, every major tech company was racing to build deep learning teams. Within five years, deep learning had conquered computer vision, speech recognition, machine translation, and game-playing.</p>
<p>The breakthroughs came in waves. <strong>Generative Adversarial Networks</strong> (2014) opened the door to AI-generated images. <strong>AlphaGo</strong> (2016) defeated the world’s best Go player, a feat experts had predicted was decades away. The <strong>Transformer</strong> architecture (2017) replaced recurrence with self-attention and became the foundation for all modern language models. <strong>BERT</strong> (2018) and the <strong>GPT</strong> series (2018–2020) demonstrated that massive pretrained models could achieve state-of-the-art results across dozens of language tasks — culminating in <strong>GPT-3</strong>, whose 175 billion parameters produced text so fluent it blurred the line between human and machine.</p>
<p>At the same time, AI became deeply embedded in everyday life. Voice assistants like <strong>Siri</strong> and <strong>Alexa</strong> reached hundreds of millions of users. <strong>Waymo</strong> launched the first fully driverless taxi service. Recommendation engines, fraud detection, and search algorithms powered by deep learning became invisible infrastructure. And alongside the excitement, serious ethical debates emerged — about bias, fairness, deepfakes, and the responsibility of building systems whose inner workings we barely understand.</p>
<p>This article traces the key milestones of the 2010s — from the AlexNet moment that launched the deep learning era, through the game-playing triumphs and architectural innovations, to the birth of large language models that would define the next decade.</p>
</section>
<section id="timeline-of-key-milestones" class="level2">
<h2 class="anchored" data-anchor-id="timeline-of-key-milestones">Timeline of Key Milestones</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'fontSize': '14px'}}}%%
timeline
    title 2010s AI Milestones — Deep Learning Revolution and Modern AI
    2011 : IBM Watson defeats Jeopardy! champions Ken Jennings and Brad Rutter
         : Apple releases Siri — AI personal assistant goes mainstream
    2012 : AlexNet wins ImageNet with 15.3% top-5 error — deep learning revolution begins
    2013 : Tomas Mikolov introduces Word2Vec — word embeddings capture semantics
         : DeepMind unveils Deep Q-Network — learns Atari games from pixels
    2014 : Ian Goodfellow introduces GANs — generative adversarial networks
         : Facebook announces DeepFace — near-human face recognition
         : Amazon launches Alexa — voice AI enters the home
    2015 : Microsoft introduces ResNet — 152 layers with residual connections
         : Google releases DeepDream — AI-generated art enters public consciousness
         : DQN paper published in Nature
    2016 : AlphaGo defeats Lee Sedol 4-1 in Go — a watershed moment
    2017 : Transformer architecture — "Attention Is All You Need"
         : AlphaGo Zero learns from scratch — defeats original AlphaGo 100-0
         : AlphaZero masters Go, chess, and shogi in 24 hours
    2018 : Google releases BERT — bidirectional pretrained language model
         : OpenAI introduces GPT-1 — 117 million parameters
    2019 : OpenAI releases GPT-2 — 1.5 billion parameters
         : DeepMind's AlphaStar reaches Grandmaster in StarCraft II
    2020 : OpenAI releases GPT-3 — 175 billion parameters, few-shot learning
         : Waymo launches Waymo One — first fully driverless taxi service
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="ibm-watson-defeats-jeopardy-champions-2011" class="level2">
<h2 class="anchored" data-anchor-id="ibm-watson-defeats-jeopardy-champions-2011">IBM Watson Defeats Jeopardy! Champions (2011)</h2>
<p>In February 2011, <strong>IBM’s Watson</strong> defeated <strong>Ken Jennings</strong> and <strong>Brad Rutter</strong> — the two greatest <em>Jeopardy!</em> champions — in a nationally televised match. Watson combined natural language processing, probabilistic reasoning, information retrieval, and ensemble machine learning methods to parse complex questions and retrieve answers in real time.</p>
<p>Watson processed the equivalent of a million books of text — including encyclopedias, dictionaries, news articles, and literary works — to build its knowledge base. It used over 100 different analytical techniques simultaneously, then weighted the confidence of each to select the most likely answer.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Date</strong></td>
<td>February 14–16, 2011</td>
</tr>
<tr class="even">
<td><strong>System</strong></td>
<td>IBM Watson</td>
</tr>
<tr class="odd">
<td><strong>Opponents</strong></td>
<td>Ken Jennings (74-game winner), Brad Rutter (all-time earnings leader)</td>
</tr>
<tr class="even">
<td><strong>Results</strong></td>
<td>Watson: $77,147; Jennings: $24,000; Rutter: $21,600</td>
</tr>
<tr class="odd">
<td><strong>Technology</strong></td>
<td>NLP, information retrieval, probabilistic reasoning, ensemble ML</td>
</tr>
<tr class="even">
<td><strong>Hardware</strong></td>
<td>90 IBM Power 750 servers, 2,880 processor cores, 16 TB RAM</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>First AI to compete at expert level in open-domain question answering</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Ken Jennings famously wrote on his Final Jeopardy answer: “I for one welcome our new computer overlords.”</p>
</blockquote>
<p>For the public, Watson was as dramatic as Deep Blue’s chess victory in 1997 — proof that machines could now challenge humans in the domain of natural language and general knowledge. Watson also demonstrated that combining many weaker AI techniques could produce a system far more capable than any single approach.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["Natural Language&lt;br/&gt;Processing"] --&gt; E["Watson&lt;br/&gt;DeepQA Architecture"]
    B["Information&lt;br/&gt;Retrieval"] --&gt; E
    C["Probabilistic&lt;br/&gt;Reasoning"] --&gt; E
    D["Machine Learning&lt;br/&gt;Ensembles"] --&gt; E
    E --&gt; F["Candidate Answer&lt;br/&gt;Generation"]
    F --&gt; G["Evidence Scoring&lt;br/&gt;&amp; Confidence Ranking"]
    G --&gt; H["Final Answer&lt;br/&gt;Selection"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#e74c3c,color:#fff,stroke:#333
    style C fill:#27ae60,color:#fff,stroke:#333
    style D fill:#8e44ad,color:#fff,stroke:#333
    style E fill:#f39c12,color:#fff,stroke:#333
    style F fill:#2980b9,color:#fff,stroke:#333
    style G fill:#1a5276,color:#fff,stroke:#333
    style H fill:#e67e22,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="siri-and-the-rise-of-voice-assistants-2011" class="level2">
<h2 class="anchored" data-anchor-id="siri-and-the-rise-of-voice-assistants-2011">Siri and the Rise of Voice Assistants (2011)</h2>
<p>In October 2011, <strong>Apple released Siri</strong> on the iPhone 4S, bringing AI-powered personal assistance into the mainstream. Siri combined speech recognition, natural language understanding, and task execution to let users make calls, send messages, set reminders, and search the web using natural voice commands.</p>
<p>Siri originated from a DARPA-funded project called <strong>CALO</strong> (Cognitive Assistant that Learns and Organizes) at SRI International. The research team spun off Siri Inc.&nbsp;in 2007, and Apple acquired the company in 2010. When Apple integrated Siri into the iPhone, it instantly reached hundreds of millions of users — making conversational AI a daily experience for consumers worldwide.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Released</strong></td>
<td>October 14, 2011 (iPhone 4S)</td>
</tr>
<tr class="even">
<td><strong>Origin</strong></td>
<td>DARPA CALO project at SRI International</td>
</tr>
<tr class="odd">
<td><strong>Acquired by Apple</strong></td>
<td>2010</td>
</tr>
<tr class="even">
<td><strong>Capabilities</strong></td>
<td>Speech recognition, NLU, task execution, web search</td>
</tr>
<tr class="odd">
<td><strong>Impact</strong></td>
<td>First mass-market AI personal assistant</td>
</tr>
<tr class="even">
<td><strong>Followed by</strong></td>
<td>Google Now (2012), Amazon Alexa (2014), Microsoft Cortana (2014)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Siri proved that AI didn’t need to pass the Turing test to be useful — it just had to understand what you meant well enough to be helpful.</p>
</blockquote>
<p>Siri launched a voice assistant arms race. Google released <strong>Google Now</strong> in 2012, Amazon launched <strong>Alexa</strong> in 2014 as an always-on home assistant, and Microsoft introduced <strong>Cortana</strong> the same year. By the end of the decade, hundreds of millions of people interacted with AI assistants daily — a scale of human-AI interaction that would have seemed like science fiction just a few years earlier.</p>
</section>
<section id="alexnet-the-imagenet-breakthrough-2012" class="level2">
<h2 class="anchored" data-anchor-id="alexnet-the-imagenet-breakthrough-2012">AlexNet: The ImageNet Breakthrough (2012)</h2>
<p>In September 2012, <strong>Alex Krizhevsky</strong>, <strong>Ilya Sutskever</strong>, and <strong>Geoffrey Hinton</strong> submitted AlexNet to the ImageNet Large Scale Visual Recognition Challenge — and changed the course of artificial intelligence. With eight layers, 60 million parameters, and training on two NVIDIA GTX 580 GPUs, AlexNet achieved a top-5 error rate of <strong>15.3%</strong> — more than <strong>10.8 percentage points</strong> better than the runner-up. The gap was so vast that it effectively ended the debate about whether deep neural networks could compete with hand-crafted feature engineering.</p>
<p>AlexNet’s architecture was not radically new — it was essentially a scaled-up version of Yann LeCun’s LeNet from the late 1980s. What made it revolutionary was the convergence of three ingredients: the <strong>massive ImageNet dataset</strong> (1.2 million labeled images), <strong>GPU-accelerated training</strong> via NVIDIA’s CUDA platform, and <strong>algorithmic refinements</strong> including ReLU activation functions and dropout regularization.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Submitted</strong></td>
<td>September 30, 2012 (ILSVRC)</td>
</tr>
<tr class="even">
<td><strong>Creators</strong></td>
<td>Alex Krizhevsky, Ilya Sutskever, Geoffrey Hinton (University of Toronto)</td>
</tr>
<tr class="odd">
<td><strong>Architecture</strong></td>
<td>8 layers (5 convolutional + 3 fully connected), 60M parameters</td>
</tr>
<tr class="even">
<td><strong>Training hardware</strong></td>
<td>2 × NVIDIA GTX 580 GPUs (3 GB each), 5–6 days</td>
</tr>
<tr class="odd">
<td><strong>Top-5 error</strong></td>
<td>15.3% (runner-up: 26.2%)</td>
</tr>
<tr class="even">
<td><strong>Key innovations</strong></td>
<td>ReLU activation, dropout regularization, data augmentation, GPU training</td>
</tr>
<tr class="odd">
<td><strong>Impact</strong></td>
<td>Launched the deep learning revolution in computer vision</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Yann LeCun, upon seeing AlexNet’s results at ECCV 2012, called it “an unequivocal turning point in the history of computer vision.”</p>
</blockquote>
<p>Fei-Fei Li, who created the ImageNet dataset, reflected years later: “That moment was pretty symbolic to the world of AI because three fundamental elements of modern AI converged for the first time” — data, compute, and algorithms. The three researchers formed DNNResearch and sold the company to Google, and AlexNet’s codebase was later released as open source. Within two years, deep convolutional networks had become the default approach for virtually every computer vision problem.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["ImageNet&lt;br/&gt;1.2M labeled images"] --&gt; D["AlexNet&lt;br/&gt;(2012)"]
    B["NVIDIA GPUs&lt;br/&gt;CUDA Platform"] --&gt; D
    C["Algorithmic Advances&lt;br/&gt;ReLU, Dropout,&lt;br/&gt;Data Augmentation"] --&gt; D
    D --&gt; E["15.3% Top-5 Error&lt;br/&gt;(vs 26.2% runner-up)"]
    E --&gt; F["Deep Learning&lt;br/&gt;Revolution"]
    F --&gt; G["GoogLeNet · VGGNet&lt;br/&gt;ResNet · Industry Adoption"]

    style A fill:#e74c3c,color:#fff,stroke:#333
    style B fill:#27ae60,color:#fff,stroke:#333
    style C fill:#3498db,color:#fff,stroke:#333
    style D fill:#f39c12,color:#fff,stroke:#333
    style E fill:#8e44ad,color:#fff,stroke:#333
    style F fill:#1a5276,color:#fff,stroke:#333
    style G fill:#2c3e50,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="word2vec-learning-the-semantics-of-language-2013" class="level2">
<h2 class="anchored" data-anchor-id="word2vec-learning-the-semantics-of-language-2013">Word2Vec: Learning the Semantics of Language (2013)</h2>
<p>In 2013, <strong>Tomas Mikolov</strong> and colleagues at Google introduced <strong>Word2Vec</strong> — a method for learning dense vector representations of words (word embeddings) from large text corpora. Word2Vec captured semantic relationships in vector arithmetic: the famous example that <em>“king” − “man” + “woman” ≈ “queen”</em> demonstrated that the model had learned meaningful relationships between concepts.</p>
<p>Word2Vec offered two architectures — <strong>Continuous Bag-of-Words</strong> (CBOW), which predicted a word from its context, and <strong>Skip-gram</strong>, which predicted context from a word. Both were simple, fast to train, and produced embeddings that transferred remarkably well across tasks.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>2013</td>
</tr>
<tr class="even">
<td><strong>Author</strong></td>
<td>Tomas Mikolov et al.&nbsp;(Google)</td>
</tr>
<tr class="odd">
<td><strong>Method</strong></td>
<td>Shallow neural networks learning distributed word representations</td>
</tr>
<tr class="even">
<td><strong>Architectures</strong></td>
<td>CBOW (predict word from context) and Skip-gram (predict context from word)</td>
</tr>
<tr class="odd">
<td><strong>Famous result</strong></td>
<td>king − man + woman ≈ queen</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Foundation for modern NLP; precursor to contextual embeddings (ELMo, BERT)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Word2Vec showed that language has geometry — that meanings live in a space where arithmetic operations correspond to semantic relationships.</p>
</blockquote>
<p>Word2Vec and its successors (<strong>GloVe</strong>, <strong>FastText</strong>) became the standard input representation for NLP systems throughout the mid-2010s. More importantly, they demonstrated a key principle: that <strong>unsupervised pretraining on large corpora</strong> could capture rich linguistic knowledge — an insight that would later scale to transformers and large language models.</p>
</section>
<section id="deep-q-network-reinforcement-learning-from-pixels-20132015" class="level2">
<h2 class="anchored" data-anchor-id="deep-q-network-reinforcement-learning-from-pixels-20132015">Deep Q-Network: Reinforcement Learning from Pixels (2013–2015)</h2>
<p>In 2013, a small London startup called <strong>DeepMind</strong> demonstrated a system that could learn to play <strong>Atari 2600 games</strong> directly from raw pixel inputs, reaching superhuman performance in titles like <em>Breakout</em>, <em>Enduro</em>, and <em>Pong</em>. The <strong>Deep Q-Network</strong> (DQN) combined convolutional neural networks with Q-learning — a form of reinforcement learning — to learn policies entirely from experience, without any human-designed features.</p>
<p>The results were published in <em>Nature</em> in 2015, marking the first time a deep reinforcement learning paper appeared in the journal. DQN used the same architecture and hyperparameters across 49 different Atari games, demonstrating a remarkable level of generality for an RL system.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Demonstrated</strong></td>
<td>2013 (preprint); 2015 (<em>Nature</em> publication)</td>
</tr>
<tr class="even">
<td><strong>Organization</strong></td>
<td>DeepMind</td>
</tr>
<tr class="odd">
<td><strong>Method</strong></td>
<td>Deep convolutional network + Q-learning (experience replay, target network)</td>
</tr>
<tr class="even">
<td><strong>Input</strong></td>
<td>Raw pixels from Atari 2600 games</td>
</tr>
<tr class="odd">
<td><strong>Performance</strong></td>
<td>Superhuman in 29 of 49 Atari games tested</td>
</tr>
<tr class="even">
<td><strong>Key innovations</strong></td>
<td>Experience replay buffer, fixed target network for stability</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Launched the field of deep reinforcement learning</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>DQN proved that a single learning algorithm, with no game-specific knowledge, could master dozens of different tasks from raw sensory input — a step toward general-purpose AI.</p>
</blockquote>
<p>Google acquired DeepMind in January 2014 for approximately £400 million, one of the largest AI acquisitions in history at the time. DQN’s success directly led to AlphaGo and the broader deep reinforcement learning revolution that followed.</p>
</section>
<section id="generative-adversarial-networks-the-art-of-ai-creation-2014" class="level2">
<h2 class="anchored" data-anchor-id="generative-adversarial-networks-the-art-of-ai-creation-2014">Generative Adversarial Networks: The Art of AI Creation (2014)</h2>
<p>In 2014, <strong>Ian Goodfellow</strong> introduced <strong>Generative Adversarial Networks</strong> (GANs) — one of the most creative and influential ideas in modern machine learning. A GAN consists of two neural networks locked in a competitive game: a <strong>generator</strong> that creates synthetic data (such as images), and a <strong>discriminator</strong> that tries to distinguish real data from generated data. As they train against each other, both improve — the generator produces increasingly realistic outputs, and the discriminator becomes increasingly discerning.</p>
<p>The idea reportedly came to Goodfellow during a conversation with friends at a Montreal bar. He went home that evening, coded the first GAN, and it worked on the first try.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>2014 (NeurIPS)</td>
</tr>
<tr class="even">
<td><strong>Author</strong></td>
<td>Ian Goodfellow et al.&nbsp;(Université de Montréal)</td>
</tr>
<tr class="odd">
<td><strong>Architecture</strong></td>
<td>Generator vs.&nbsp;Discriminator in adversarial training</td>
</tr>
<tr class="even">
<td><strong>Key insight</strong></td>
<td>Competition between two networks drives both to improve</td>
</tr>
<tr class="odd">
<td><strong>Applications</strong></td>
<td>Image synthesis, style transfer, super-resolution, deepfakes, data augmentation</td>
</tr>
<tr class="even">
<td><strong>Variants</strong></td>
<td>DCGAN, StyleGAN, CycleGAN, Pix2Pix, BigGAN</td>
</tr>
<tr class="odd">
<td><strong>Cultural impact</strong></td>
<td>Fueled the rise of deepfakes and AI-generated media</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>GANs created a new paradigm: instead of hand-crafting generative models, let two networks compete until one learns to create outputs indistinguishable from reality.</p>
</blockquote>
<p>GANs spawned an enormous body of follow-up research. <strong>DCGAN</strong> (2015) stabilized training with convolutional architectures. <strong>StyleGAN</strong> (2018) produced photorealistic human faces. <strong>CycleGAN</strong> enabled unpaired image translation (turning horses into zebras, summer landscapes into winter scenes). And websites like “This Person Does Not Exist” later demonstrated GANs’ ability to generate photorealistic faces of people who never existed — raising serious questions about deepfakes, misinformation, and digital trust.</p>
</section>
<section id="resnet-the-power-of-depth-2015" class="level2">
<h2 class="anchored" data-anchor-id="resnet-the-power-of-depth-2015">ResNet: The Power of Depth (2015)</h2>
<p>In 2015, <strong>Kaiming He</strong> and colleagues at Microsoft Research introduced <strong>ResNet</strong> (Residual Network) — a deep neural network with <strong>152 layers</strong> that used <strong>residual connections</strong> (skip connections) to solve the degradation problem that had prevented training of very deep networks. ResNet won the ImageNet 2015 challenge with a 3.57% top-5 error rate — surpassing human-level performance for the first time on this benchmark.</p>
<p>The key insight was elegantly simple: instead of asking each layer to learn the desired mapping directly, ResNet let each layer learn the <em>residual</em> — the difference between the input and the desired output. By adding a shortcut connection that bypassed one or more layers, gradients could flow directly through the network during backpropagation, enabling training of networks far deeper than previously possible.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>2015 (CVPR 2016, Best Paper)</td>
</tr>
<tr class="even">
<td><strong>Authors</strong></td>
<td>Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun (Microsoft Research)</td>
</tr>
<tr class="odd">
<td><strong>Architecture</strong></td>
<td>152 layers with residual (skip) connections</td>
</tr>
<tr class="even">
<td><strong>ImageNet top-5 error</strong></td>
<td>3.57% (surpassed human-level ~5.1%)</td>
</tr>
<tr class="odd">
<td><strong>Key innovation</strong></td>
<td>Residual learning — layers learn F(x) = H(x) − x instead of H(x)</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Enabled training of arbitrarily deep networks; became a standard building block</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>ResNet showed that with the right architecture, there was no practical limit to network depth — and that deeper networks, properly trained, consistently outperformed shallower ones.</p>
</blockquote>
<p>ResNet’s influence was enormous. Residual connections became a standard component in virtually every deep learning architecture that followed, including transformers. The idea that you could train a 152-layer network — when just three years earlier, 8 layers had been groundbreaking — demonstrated how rapidly the field was advancing.</p>
</section>
<section id="alphago-ai-conquers-the-ancient-game-of-go-2016" class="level2">
<h2 class="anchored" data-anchor-id="alphago-ai-conquers-the-ancient-game-of-go-2016">AlphaGo: AI Conquers the Ancient Game of Go (2016)</h2>
<p>In March 2016, DeepMind’s <strong>AlphaGo</strong> defeated <strong>Lee Sedol</strong> — one of the world’s greatest Go players, ranked 9-dan — in a five-game match in Seoul, winning <strong>4 games to 1</strong>. The victory was a watershed moment: Go’s vast complexity (<span class="math inline">10^{170}</span> possible board positions) had long been considered beyond the reach of AI, and most experts had predicted it would take at least another decade before computers could compete with top professionals.</p>
<p>AlphaGo combined <strong>deep convolutional neural networks</strong> with <strong>Monte Carlo tree search</strong>. A policy network guided the search toward promising moves, while a value network evaluated board positions. The system was trained first on 30 million moves from expert human games, then refined through millions of games of self-play using reinforcement learning. For the match against Lee Sedol, AlphaGo used 1,920 CPUs and 280 GPUs.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Date</strong></td>
<td>March 9–15, 2016</td>
</tr>
<tr class="even">
<td><strong>Match</strong></td>
<td>AlphaGo vs.&nbsp;Lee Sedol (9-dan), Seoul, South Korea</td>
</tr>
<tr class="odd">
<td><strong>Result</strong></td>
<td>AlphaGo won 4–1</td>
</tr>
<tr class="even">
<td><strong>Method</strong></td>
<td>Deep neural networks + Monte Carlo tree search + reinforcement learning</td>
</tr>
<tr class="odd">
<td><strong>Training</strong></td>
<td>30M expert moves + millions of self-play games</td>
</tr>
<tr class="even">
<td><strong>Hardware</strong></td>
<td>1,920 CPUs, 280 GPUs (cloud-based)</td>
</tr>
<tr class="odd">
<td><strong>Viewership</strong></td>
<td>Over 100 million people watched the matches</td>
</tr>
<tr class="even">
<td><strong>Prize</strong></td>
<td>US$1 million (donated to charities)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Lee Sedol, after losing three consecutive games, said: “I misjudged the capabilities of AlphaGo and felt powerless.” Yet he won Game 4 with what commentators called the “divine move” — the only game any human would ever win against AlphaGo.</p>
</blockquote>
<p>The cultural impact was immense. In China, AlphaGo was a “Sputnik moment” that helped convince the government to dramatically increase funding for AI. The Netflix documentary <em>AlphaGo</em> brought the story to millions of viewers worldwide. And the victory demonstrated that deep reinforcement learning could solve problems previously considered intractable.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["Expert Human Games&lt;br/&gt;30 million moves"] --&gt; B["Policy Network&lt;br/&gt;Predicts promising moves"]
    A --&gt; C["Value Network&lt;br/&gt;Evaluates board positions"]
    B --&gt; D["Monte Carlo&lt;br/&gt;Tree Search"]
    C --&gt; D
    D --&gt; E["Self-Play&lt;br/&gt;Reinforcement Learning"]
    E --&gt; B
    E --&gt; C
    E --&gt; F["AlphaGo&lt;br/&gt;Defeats Lee Sedol 4–1"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#e74c3c,color:#fff,stroke:#333
    style C fill:#27ae60,color:#fff,stroke:#333
    style D fill:#f39c12,color:#fff,stroke:#333
    style E fill:#8e44ad,color:#fff,stroke:#333
    style F fill:#1a5276,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="alphago-zero-and-alphazero-learning-from-scratch-2017" class="level2">
<h2 class="anchored" data-anchor-id="alphago-zero-and-alphazero-learning-from-scratch-2017">AlphaGo Zero and AlphaZero: Learning from Scratch (2017)</h2>
<p>Just a year after the Lee Sedol match, DeepMind published <strong>AlphaGo Zero</strong> — a version that learned Go entirely from self-play, with <em>no human data whatsoever</em>. Starting from random play, AlphaGo Zero surpassed the strength of the version that beat Lee Sedol in just three days, and defeated the original AlphaGo <strong>100 games to 0</strong>.</p>
<p>Then, in December 2017, DeepMind generalized the approach into <strong>AlphaZero</strong> — a single algorithm that mastered <strong>Go, chess, and shogi</strong> within 24 hours of training, defeating the world’s strongest specialized programs in each game: Stockfish in chess, Elmo in shogi, and a three-day-trained AlphaGo Zero in Go.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AlphaGo Zero</strong></td>
<td>Published October 2017 in <em>Nature</em></td>
</tr>
<tr class="even">
<td><strong>Training</strong></td>
<td>Pure self-play, no human data</td>
</tr>
<tr class="odd">
<td><strong>Result</strong></td>
<td>Surpassed AlphaGo Lee in 3 days; defeated original AlphaGo 100–0</td>
</tr>
<tr class="even">
<td><strong>AlphaZero</strong></td>
<td>Published December 2017</td>
</tr>
<tr class="odd">
<td><strong>Games mastered</strong></td>
<td>Go, chess, shogi — all within 24 hours</td>
</tr>
<tr class="even">
<td><strong>Defeated</strong></td>
<td>Stockfish (chess), Elmo (shogi), AlphaGo Zero 3-day (Go)</td>
</tr>
<tr class="odd">
<td><strong>Key insight</strong></td>
<td>A single general algorithm can master multiple domains from scratch</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>AlphaZero demonstrated something profound: that a general-purpose learning algorithm, given nothing but the rules of a game, could discover strategies that surpassed all human and machine knowledge — in hours.</p>
</blockquote>
<p>The implications extended far beyond board games. AlphaZero showed that self-play combined with deep reinforcement learning could discover novel strategies that no human had ever conceived. This paradigm of <em>learning from scratch without human data</em> became a guiding philosophy for much of subsequent AI research.</p>
</section>
<section id="the-transformer-attention-is-all-you-need-2017" class="level2">
<h2 class="anchored" data-anchor-id="the-transformer-attention-is-all-you-need-2017">The Transformer: Attention Is All You Need (2017)</h2>
<p>In June 2017, a team of eight Google researchers published a paper titled <strong>“Attention Is All You Need”</strong> — and quietly laid the foundation for the entire modern AI era. The <strong>Transformer architecture</strong> replaced recurrence (LSTMs, GRUs) with a mechanism called <strong>self-attention</strong>, allowing every token in a sequence to attend to every other token in parallel. This eliminated the sequential bottleneck of recurrent networks and enabled massive parallelization during training.</p>
<p>The key idea — proposed by <strong>Jakob Uszkoreit</strong> — was that attention alone, without any recurrent or convolutional layers, could be sufficient for sequence transduction. Even his father, noted computational linguist Hans Uszkoreit, was skeptical. But the results were decisive: the original transformer, with only 100 million parameters, set new state-of-the-art results on English-to-German and English-to-French machine translation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>June 2017 (NeurIPS 2017)</td>
</tr>
<tr class="even">
<td><strong>Authors</strong></td>
<td>Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan Gomez, Łukasz Kaiser, Illia Polosukhin (Google)</td>
</tr>
<tr class="odd">
<td><strong>Key innovation</strong></td>
<td>Self-attention mechanism replacing recurrence entirely</td>
</tr>
<tr class="even">
<td><strong>Architecture</strong></td>
<td>Encoder-decoder with multi-head attention, ~100M parameters</td>
</tr>
<tr class="odd">
<td><strong>Advantages</strong></td>
<td>Massive parallelization, better long-range dependencies, scalability</td>
</tr>
<tr class="even">
<td><strong>Original task</strong></td>
<td>Machine translation (English → German, English → French)</td>
</tr>
<tr class="odd">
<td><strong>Legacy</strong></td>
<td>Foundation of BERT, GPT, T5, LLaMA, and all modern LLMs</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>The Transformer paper didn’t just introduce a new architecture — it introduced a new paradigm. Within three years, transformers had replaced RNNs and LSTMs in virtually every NLP task, and were expanding into vision, audio, and reinforcement learning.</p>
</blockquote>
<p>The eight authors of the Transformer paper went on to build or co-found some of the most influential AI organizations: OpenAI, Cohere, Inceptive, Character.AI, and others. The Transformer became the backbone of BERT, GPT, T5, PaLM, LLaMA, and every major language model that followed — arguably the most consequential machine learning architecture ever published.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["Input Sequence&lt;br/&gt;(Tokens)"] --&gt; B["Embedding +&lt;br/&gt;Positional Encoding"]
    B --&gt; C["Multi-Head&lt;br/&gt;Self-Attention"]
    C --&gt; D["Feed-Forward&lt;br/&gt;Network"]
    D --&gt; E["Layer Normalization&lt;br/&gt;+ Residual Connections"]
    E --&gt; F["Stack N Layers&lt;br/&gt;(Encoder / Decoder)"]
    F --&gt; G["Output&lt;br/&gt;Predictions"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#e74c3c,color:#fff,stroke:#333
    style C fill:#f39c12,color:#fff,stroke:#333
    style D fill:#27ae60,color:#fff,stroke:#333
    style E fill:#8e44ad,color:#fff,stroke:#333
    style F fill:#1a5276,color:#fff,stroke:#333
    style G fill:#e67e22,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="bert-bidirectional-pretrained-language-understanding-2018" class="level2">
<h2 class="anchored" data-anchor-id="bert-bidirectional-pretrained-language-understanding-2018">BERT: Bidirectional Pretrained Language Understanding (2018)</h2>
<p>In October 2018, <strong>Google</strong> released <strong>BERT</strong> (Bidirectional Encoder Representations from Transformers) — a transformer-based model pretrained on large text corpora using two self-supervised tasks: <strong>masked language modeling</strong> (predicting randomly masked words) and <strong>next sentence prediction</strong>. BERT achieved state-of-the-art results on 11 NLP benchmarks simultaneously, including question answering, sentiment analysis, and natural language inference.</p>
<p>BERT’s key innovation was <strong>bidirectionality</strong>: unlike previous language models that read text left-to-right (or right-to-left), BERT processed text in both directions simultaneously, allowing each word to attend to all surrounding context. This produced richer, more contextual word representations than anything before.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>October 2018</td>
</tr>
<tr class="even">
<td><strong>Authors</strong></td>
<td>Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova (Google AI)</td>
</tr>
<tr class="odd">
<td><strong>Architecture</strong></td>
<td>Encoder-only transformer</td>
</tr>
<tr class="even">
<td><strong>Pretraining</strong></td>
<td>Masked language modeling + next sentence prediction</td>
</tr>
<tr class="odd">
<td><strong>Variants</strong></td>
<td>BERT-Base (110M params), BERT-Large (340M params)</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>SOTA on 11 NLP benchmarks simultaneously</td>
</tr>
<tr class="odd">
<td><strong>Deployment</strong></td>
<td>Google Search adopted BERT for query understanding in October 2019</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>BERT demonstrated a powerful principle: pretrain once on a massive text corpus, then fine-tune cheaply on any downstream task. This “pretrain-then-finetune” paradigm became the standard for NLP and beyond.</p>
</blockquote>
<p>By October 2019, Google was using BERT on almost every English search query, representing one of the largest deployments of transformer-based AI in history. BERT also spawned a family of successors — RoBERTa, ALBERT, DistilBERT, XLNet — each refining the pretrain-then-finetune recipe.</p>
</section>
<section id="the-gpt-series-from-117-million-to-175-billion-parameters-20182020" class="level2">
<h2 class="anchored" data-anchor-id="the-gpt-series-from-117-million-to-175-billion-parameters-20182020">The GPT Series: From 117 Million to 175 Billion Parameters (2018–2020)</h2>
<p>While BERT focused on understanding language, OpenAI pursued a different path: <strong>generative pretraining</strong>. In June 2018, <strong>GPT-1</strong> demonstrated that a decoder-only transformer with 117 million parameters, pretrained on a large text corpus, could be fine-tuned to achieve strong performance on various NLP tasks.</p>
<p>In February 2019, <strong>GPT-2</strong> scaled to 1.5 billion parameters — and produced text so coherent and diverse that OpenAI initially withheld the full model due to concerns about misuse. GPT-2 could generate realistic news articles, stories, and technical prose that was often difficult to distinguish from human writing.</p>
<p>Then came <strong>GPT-3</strong> in June 2020, with <strong>175 billion parameters</strong> trained on hundreds of billions of words. GPT-3 demonstrated <strong>few-shot learning</strong>: given just a few examples in a prompt, it could perform tasks it had never been explicitly trained for — translation, summarization, question answering, code generation, and more. No fine-tuning required.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Date</th>
<th>Parameters</th>
<th>Key Advance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>GPT-1</strong></td>
<td>June 2018</td>
<td>117M</td>
<td>Generative pretraining + fine-tuning</td>
</tr>
<tr class="even">
<td><strong>GPT-2</strong></td>
<td>Feb 2019</td>
<td>1.5B</td>
<td>Coherent long-form text generation</td>
</tr>
<tr class="odd">
<td><strong>GPT-3</strong></td>
<td>June 2020</td>
<td>175B</td>
<td>Few-shot learning without fine-tuning</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>GPT-3 captured worldwide attention — not because it was perfect, but because it demonstrated that scale alone could produce emergent capabilities that no one had explicitly programmed.</p>
</blockquote>
<p>GPT-3’s capabilities were both thrilling and unsettling. It could write poetry, debug code, answer trivia questions, and generate business emails — but it could also produce plausible misinformation, biased content, and confidently wrong answers. The release marked a turning point: language models were no longer academic curiosities. They were technologies with the power to reshape how humans communicate, create, and think.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["GPT-1 (2018)&lt;br/&gt;117M params"] --&gt; B["GPT-2 (2019)&lt;br/&gt;1.5B params"]
    B --&gt; C["GPT-3 (2020)&lt;br/&gt;175B params"]
    C --&gt; D["Few-Shot Learning&lt;br/&gt;Emergent Capabilities"]
    D --&gt; E["Code Generation&lt;br/&gt;Translation · QA&lt;br/&gt;Creative Writing"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#e67e22,color:#fff,stroke:#333
    style C fill:#e74c3c,color:#fff,stroke:#333
    style D fill:#8e44ad,color:#fff,stroke:#333
    style E fill:#1a5276,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="alphastar-mastering-real-time-strategy-2019" class="level2">
<h2 class="anchored" data-anchor-id="alphastar-mastering-real-time-strategy-2019">AlphaStar: Mastering Real-Time Strategy (2019)</h2>
<p>In October 2019, DeepMind’s <strong>AlphaStar</strong> reached <strong>Grandmaster level</strong> in the real-time strategy game <em>StarCraft II</em> — one of the most complex competitive games in the world. Unlike board games such as Go or chess, StarCraft II involves <strong>imperfect information</strong>, <strong>real-time decision-making</strong>, thousands of possible actions per timestep, and long-term strategic planning over matches lasting 10–30 minutes.</p>
<p>AlphaStar trained through a combination of supervised learning from human replays and multi-agent reinforcement learning, where agents in a “league” competed against each other to develop diverse strategies. It reached Grandmaster on the official Battle.net ladder — placing above 99.8% of human players.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Announced</strong></td>
<td>January 2019; October 2019 (Grandmaster)</td>
</tr>
<tr class="even">
<td><strong>Organization</strong></td>
<td>DeepMind</td>
</tr>
<tr class="odd">
<td><strong>Game</strong></td>
<td>StarCraft II (Blizzard Entertainment)</td>
</tr>
<tr class="even">
<td><strong>Method</strong></td>
<td>Supervised learning + multi-agent reinforcement learning</td>
</tr>
<tr class="odd">
<td><strong>Level achieved</strong></td>
<td>Grandmaster (top 0.2% of players on Battle.net)</td>
</tr>
<tr class="even">
<td><strong>Challenges</strong></td>
<td>Imperfect information, real-time play, huge action space, long horizons</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>First AI to reach top tier in a major real-time strategy game</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>AlphaStar showed that deep reinforcement learning could handle real-time, imperfect-information environments far more complex than any board game — pushing AI closer to the messiness of real-world decision-making.</p>
</blockquote>
</section>
<section id="waymo-and-the-road-to-autonomous-driving-20182020" class="level2">
<h2 class="anchored" data-anchor-id="waymo-and-the-road-to-autonomous-driving-20182020">Waymo and the Road to Autonomous Driving (2018–2020)</h2>
<p>Throughout the 2010s, <strong>autonomous driving</strong> advanced from DARPA Challenge prototypes to vehicles operating on public roads. <strong>Waymo</strong> — Google’s self-driving car project, spun off as a separate company in 2016 — led the effort, logging millions of miles of autonomous driving on public roads in Arizona, California, and other states.</p>
<p>In December 2018, Waymo launched <strong>Waymo One</strong>, a commercial ride-hailing service using autonomous vehicles in the Phoenix, Arizona metro area — initially with safety drivers, then expanding to <strong>fully driverless rides</strong> in 2020. It was the world’s first commercial autonomous taxi service.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Origin</strong></td>
<td>Google Self-Driving Car Project (2009)</td>
</tr>
<tr class="even">
<td><strong>Spun off</strong></td>
<td>Waymo (December 2016)</td>
</tr>
<tr class="odd">
<td><strong>Waymo One launch</strong></td>
<td>December 2018 (with safety drivers)</td>
</tr>
<tr class="even">
<td><strong>Fully driverless</strong></td>
<td>2020 (Phoenix, AZ)</td>
</tr>
<tr class="odd">
<td><strong>Miles driven</strong></td>
<td>Over 20 million autonomous miles by end of decade</td>
</tr>
<tr class="even">
<td><strong>Technology</strong></td>
<td>LIDAR, cameras, radar, ML-based perception and planning</td>
</tr>
</tbody>
</table>
<p>However, the decade also brought sobering reminders of the technology’s limitations. In March 2018, an <strong>Uber self-driving vehicle</strong> struck and killed a pedestrian in Tempe, Arizona — the first known fatality involving a fully autonomous vehicle. The incident underscored the critical importance of safety engineering, regulation, and public trust in deploying AI in safety-critical applications.</p>
</section>
<section id="consumer-ai-and-the-invisible-revolution-2010s" class="level2">
<h2 class="anchored" data-anchor-id="consumer-ai-and-the-invisible-revolution-2010s">Consumer AI and the Invisible Revolution (2010s)</h2>
<p>While researchers competed for benchmark records and headlines, AI was quietly becoming the <strong>invisible infrastructure of daily life</strong>. By the end of the decade, deep learning powered an extraordinary range of consumer applications that billions of people used without thinking of them as “AI.”</p>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 42%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Application</th>
<th>AI Technology</th>
<th>Scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Google Search</strong></td>
<td>Deep learning ranking, BERT</td>
<td>Billions of queries/day</td>
</tr>
<tr class="even">
<td><strong>Google Translate</strong></td>
<td>Neural machine translation (2016)</td>
<td>100+ languages</td>
</tr>
<tr class="odd">
<td><strong>Gmail Smart Reply</strong></td>
<td>Seq2seq neural networks</td>
<td>Hundreds of millions of users</td>
</tr>
<tr class="even">
<td><strong>Netflix / YouTube</strong></td>
<td>Deep learning recommendations</td>
<td>Billions of hours of content</td>
</tr>
<tr class="odd">
<td><strong>Facebook News Feed</strong></td>
<td>Deep learning ranking and content understanding</td>
<td>2+ billion users</td>
</tr>
<tr class="even">
<td><strong>Siri / Alexa / Google Assistant</strong></td>
<td>Speech recognition + NLU + deep learning</td>
<td>Hundreds of millions of devices</td>
</tr>
<tr class="odd">
<td><strong>Smartphone cameras</strong></td>
<td>Neural network photo enhancement, portrait mode</td>
<td>Billions of photos/day</td>
</tr>
<tr class="even">
<td><strong>Fraud detection</strong></td>
<td>Deep anomaly detection, graph neural networks</td>
<td>Trillions of transactions</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>The most transformative AI of the 2010s wasn’t in research papers — it was in the services people used every day, making search smarter, translation instant, and photos sharper.</p>
</blockquote>
<p>In 2016, Google replaced its decade-old phrase-based translation system with <strong>Google Neural Machine Translation</strong> (GNMT), an end-to-end deep learning system. The switch — which took nine months to develop, versus ten years for the statistical system — produced translations that were dramatically more fluent. Similar transitions happened across the industry as deep learning replaced traditional ML in product after product.</p>
</section>
<section id="ai-ethics-the-reckoning-2010s2020" class="level2">
<h2 class="anchored" data-anchor-id="ai-ethics-the-reckoning-2010s2020">AI Ethics: The Reckoning (2010s–2020)</h2>
<p>As AI systems grew more powerful and pervasive, the 2010s saw the emergence of <strong>serious ethical debates</strong> that would define the next era of AI development. The issues were wide-ranging:</p>
<p><strong>Bias and fairness:</strong> Studies revealed that facial recognition systems performed significantly worse on darker-skinned faces, that hiring algorithms could discriminate against women, and that language models absorbed and amplified societal biases present in their training data.</p>
<p><strong>Deepfakes and misinformation:</strong> GAN-generated synthetic media raised concerns about trust, authenticity, and the potential for political manipulation.</p>
<p><strong>Safety-critical AI:</strong> The 2018 Uber self-driving fatality and other incidents highlighted the risks of deploying AI in life-or-death situations before the technology was sufficiently reliable.</p>
<p><strong>Accountability and transparency:</strong> The “black-box” nature of deep learning models — where billions of parameters make decisions through processes that are difficult for humans to interpret — raised fundamental questions about who is responsible when AI systems fail.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Key Examples</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bias in facial recognition</strong></td>
<td>MIT study showed higher error rates for darker-skinned faces</td>
</tr>
<tr class="even">
<td><strong>Deepfakes</strong></td>
<td>GAN-generated synthetic faces, videos, and audio</td>
</tr>
<tr class="odd">
<td><strong>Autonomous vehicle safety</strong></td>
<td>Uber self-driving fatality (March 2018)</td>
</tr>
<tr class="even">
<td><strong>Language model bias</strong></td>
<td>GPT-2/3 amplifying stereotypes from training data</td>
</tr>
<tr class="odd">
<td><strong>Surveillance</strong></td>
<td>Mass deployment of facial recognition by governments</td>
</tr>
<tr class="even">
<td><strong>Job displacement</strong></td>
<td>Automation anxiety as AI expanded into knowledge work</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>The 2010s taught the AI community an uncomfortable lesson: building powerful systems is not enough. The question of <em>how</em> those systems affect people — and who they affect most — is just as important as whether they work.</p>
</blockquote>
<p>By the end of the decade, conferences like NeurIPS (whose attendance soared past 13,000 in 2019) had added ethics tracks, fairness workshops, and impact statements. Organizations like the Partnership on AI, AI Now Institute, and numerous academic centers were established to study the societal implications of artificial intelligence.</p>
</section>
<section id="anatomy-of-the-deep-learning-revolution" class="level2">
<h2 class="anchored" data-anchor-id="anatomy-of-the-deep-learning-revolution">Anatomy of the Deep Learning Revolution</h2>
<p>Looking across the 2010s, the decade’s achievements rested on a remarkable convergence of factors:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["Large Datasets&lt;br/&gt;ImageNet, Wikipedia,&lt;br/&gt;Common Crawl"] --&gt; E["Deep Learning&lt;br/&gt;Revolution"]
    B["GPU Computing&lt;br/&gt;CUDA, TPUs,&lt;br/&gt;Cloud Infrastructure"] --&gt; E
    C["Architectural Innovation&lt;br/&gt;CNNs, GANs, Transformers,&lt;br/&gt;Residual Connections"] --&gt; E
    D["Scaling Laws&lt;br/&gt;More data + more compute&lt;br/&gt;= better performance"] --&gt; E
    E --&gt; F["Computer Vision&lt;br/&gt;AlexNet → ResNet"]
    E --&gt; G["Game-Playing AI&lt;br/&gt;DQN → AlphaGo → AlphaZero"]
    E --&gt; H["Language Models&lt;br/&gt;Word2Vec → BERT → GPT-3"]
    E --&gt; I["Consumer AI&lt;br/&gt;Siri → Alexa → Google Translate"]

    style A fill:#e74c3c,color:#fff,stroke:#333
    style B fill:#27ae60,color:#fff,stroke:#333
    style C fill:#3498db,color:#fff,stroke:#333
    style D fill:#8e44ad,color:#fff,stroke:#333
    style E fill:#f39c12,color:#fff,stroke:#333
    style F fill:#2c3e50,color:#fff,stroke:#333
    style G fill:#1a5276,color:#fff,stroke:#333
    style H fill:#2980b9,color:#fff,stroke:#333
    style I fill:#e67e22,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 34%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Early 2010s</th>
<th>Late 2010s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Leading architecture</strong></td>
<td>AlexNet (8 layers, 60M params)</td>
<td>GPT-3 (96 layers, 175B params)</td>
</tr>
<tr class="even">
<td><strong>Training hardware</strong></td>
<td>2 consumer GPUs</td>
<td>Thousands of TPUs / GPU clusters</td>
</tr>
<tr class="odd">
<td><strong>Computer vision</strong></td>
<td>Hand-crafted features</td>
<td>End-to-end deep learning</td>
</tr>
<tr class="even">
<td><strong>NLP</strong></td>
<td>Word2Vec, bag-of-words</td>
<td>BERT, GPT, transformer-based</td>
</tr>
<tr class="odd">
<td><strong>Game AI</strong></td>
<td>Atari from pixels</td>
<td>Go, chess, StarCraft at superhuman level</td>
</tr>
<tr class="even">
<td><strong>Consumer AI</strong></td>
<td>Siri (basic commands)</td>
<td>Google Translate (neural), smart cameras, deepfakes</td>
</tr>
<tr class="odd">
<td><strong>AI labs</strong></td>
<td>University research groups</td>
<td>Google Brain, DeepMind, FAIR, OpenAI</td>
</tr>
<tr class="even">
<td><strong>Industry investment</strong></td>
<td>Emerging</td>
<td>Tens of billions of dollars annually</td>
</tr>
<tr class="odd">
<td><strong>Ethics awareness</strong></td>
<td>Minimal</td>
<td>Active debate, conferences, regulation proposals</td>
</tr>
</tbody>
</table>
<p>By 2020, AI was no longer just a scientific pursuit. It was a central technology shaping business, culture, and everyday life — and raising profound questions about the future.</p>
</section>
<section id="video-2010s-ai-milestones-deep-learning-revolution-and-modern-ai" class="level2">
<h2 class="anchored" data-anchor-id="video-2010s-ai-milestones-deep-learning-revolution-and-modern-ai">Video: 2010s AI Milestones — Deep Learning Revolution and Modern AI</h2>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/E7sgXYwmuuM" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<blockquote class="blockquote">
<p>Please subscribe to the <a href="https://www.youtube.com/@vectoringai">Vectoring AI YouTube channel</a> for more video tutorials 🚀</p>
</blockquote>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Krizhevsky, A., Sutskever, I. &amp; Hinton, G. E. “ImageNet Classification with Deep Convolutional Neural Networks.” <em>Advances in Neural Information Processing Systems</em> 25 (2012). <a href="https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf">papers.nips.cc</a></li>
<li>Silver, D. et al.&nbsp;“Mastering the Game of Go with Deep Neural Networks and Tree Search.” <em>Nature</em> 529, 484–489 (2016).</li>
<li>Silver, D. et al.&nbsp;“Mastering the Game of Go without Human Knowledge.” <em>Nature</em> 550, 354–359 (2017).</li>
<li>Silver, D. et al.&nbsp;“A General Reinforcement Learning Algorithm that Masters Chess, Shogi, and Go through Self-Play.” <em>Science</em> 362(6419), 1140–1144 (2018).</li>
<li>Vaswani, A. et al.&nbsp;“Attention Is All You Need.” <em>Advances in Neural Information Processing Systems</em> 30 (2017).</li>
<li>Devlin, J. et al.&nbsp;“BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding.” <em>arXiv:1810.04805</em> (2018).</li>
<li>Radford, A. et al.&nbsp;“Improving Language Understanding by Generative Pre-Training.” OpenAI (2018).</li>
<li>Brown, T. et al.&nbsp;“Language Models Are Few-Shot Learners.” <em>Advances in Neural Information Processing Systems</em> 33 (2020).</li>
<li>Goodfellow, I. et al.&nbsp;“Generative Adversarial Nets.” <em>Advances in Neural Information Processing Systems</em> 27 (2014).</li>
<li>Mikolov, T. et al.&nbsp;“Efficient Estimation of Word Representations in Vector Space.” <em>arXiv:1301.3781</em> (2013).</li>
<li>Mnih, V. et al.&nbsp;“Human-level Control through Deep Reinforcement Learning.” <em>Nature</em> 518, 529–533 (2015).</li>
<li>He, K. et al.&nbsp;“Deep Residual Learning for Image Recognition.” <em>CVPR</em> (2016). Best Paper Award.</li>
<li>Vinyamuri, R. et al.&nbsp;“AlphaStar: Mastering the Real-Time Strategy Game StarCraft II.” DeepMind Blog (2019).</li>
<li>Ferrucci, D. et al.&nbsp;“Building Watson: An Overview of the DeepQA Project.” <em>AI Magazine</em> 31(3), 59–79 (2010).</li>
<li>Russell, S. &amp; Norvig, P. <em>Artificial Intelligence: A Modern Approach.</em> 4th ed., Pearson (2021).</li>
<li>Wikipedia. “AlexNet.” <a href="https://en.wikipedia.org/wiki/AlexNet">en.wikipedia.org/wiki/AlexNet</a></li>
<li>Wikipedia. “AlphaGo.” <a href="https://en.wikipedia.org/wiki/AlphaGo">en.wikipedia.org/wiki/AlphaGo</a></li>
<li>Wikipedia. “Transformer (deep learning).” <a href="https://en.wikipedia.org/wiki/Transformer_(deep_learning_architecture)">en.wikipedia.org/wiki/Transformer_(deep_learning_architecture)</a></li>
</ul>
</section>
<section id="read-more" class="level2">
<h2 class="anchored" data-anchor-id="read-more">Read More</h2>
<ul>
<li>See the decade that built the infrastructure — <a href="../..\posts/milestone/2000s AI Milestones.html">2000s AI Milestones</a></li>
<li>The data-driven revolution that preceded deep learning — <a href="../..\posts/milestone/1990s AI Milestones.html">1990s AI Milestones</a></li>
<li>From expert systems to the second AI winter — <a href="../..\posts/milestone/1980s AI Milestones.html">1980s AI Milestones</a></li>
<li>The first AI winter and the seeds of recovery — <a href="../..\posts/milestone/1970s AI Milestones.html">1970s AI Milestones</a></li>
<li>Where it all began — <a href="../..\posts/milestone/1950s-1960s AI Milestones.html">1950s–1960s AI Milestones</a></li>
<li>How transformers power modern language models — <a href="../..\posts/llm/Pre-training LLMs from Scratch.html">Pre-training LLMs from Scratch</a></li>
<li>Modern methods for aligning LLMs — <a href="../..\posts/llm/Post-Training LLMs for Human Alignment.html">Post-Training LLMs for Human Alignment</a></li>
<li>From prompts to context — <a href="../..\posts/llm/Prompt Engineering vs Context Engineering.html">Prompt Engineering vs Context Engineering</a></li>
<li>Scaling inference for production — <a href="../..\posts/llm/Scaling LLM Serving for Enterprise Production.html">Scaling LLM Serving for Enterprise Production</a></li>
</ul>
<!-- nav-buttons -->
<p><a href="../../pages/milestone.html" class="btn btn-primary btn-lg"><i class="fa-solid fa-flag-checkered" aria-label="flag-checkered"></i> Explore Milestones</a> <a href="../../index.html" class="btn btn-primary btn-lg"><i class="fa-solid fa-house" aria-label="house"></i> Home</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/vectoringai\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><i class="fa-regular fa-copyright" aria-label="copyright"></i> 2025-2026 Vectoring AI. All rights reserved. | <a href="../..\pages/privacy.html">Privacy Policy</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>