<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-09-24">

<title>2020–2025 AI Milestones – Vectoring AI</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../..//images/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dbc92dda8186f57fa2e333fbb71d6a9d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-23f3439e4bd86aeeff5ff0174c43dd13.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9738638303661485" crossorigin="anonymous"></script>
<!-- Cookie Consent Banner (GDPR compliant) -->
<style>
#cookie-consent-banner {
  display: none;
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #1d1d1d !important;
  color: #ffffff !important;
  padding: 16px 24px;
  z-index: 9999;
  font-size: 14px;
  box-shadow: 0 -2px 10px rgba(0,0,0,0.3);
}
#cookie-consent-banner p {
  margin: 0 0 12px 0;
  line-height: 1.5;
  color: #ffffff !important;
}
#cookie-consent-banner a {
  color: #78b9ff;
  text-decoration: underline;
}
#cookie-consent-buttons {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}
#cookie-consent-buttons button {
  padding: 8px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: 600;
}
#btn-accept-all {
  background: #3B70FE;
  color: #fff;
}
#btn-accept-essential {
  background: #555;
  color: #fff;
}
#btn-deny {
  background: transparent;
  color: #ccc;
  border: 1px solid #666 !important;
}
</style>

<meta property="og:title" content="2020–2025 AI Milestones – Vectoring AI">
<meta property="og:description" content="ChatGPT Moments, Generative AI &amp; Agentic AI — how large language models, diffusion models, and autonomous agents reshaped civilization">
<meta property="og:image" content="https://vectoringai.com//images/milestone/2020-2025-ai-milestones-300px.png">
<meta property="og:site_name" content="Vectoring AI">
<meta property="og:image:height" content="200">
<meta property="og:image:width" content="300">
<meta name="twitter:title" content="2020–2025 AI Milestones – Vectoring AI">
<meta name="twitter:description" content="ChatGPT Moments, Generative AI &amp; Agentic AI — how large language models, diffusion models, and autonomous agents reshaped civilization">
<meta name="twitter:image" content="https://vectoringai.com//images/milestone/2020-2025-ai-milestones-300px.png">
<meta name="twitter:image-height" content="200">
<meta name="twitter:image-width" content="300">
<meta name="twitter:card" content="summary_large_image">
</head><body class="nav-sidebar docked quarto-light"><div id="cookie-consent-banner">
  <p>We use cookies to serve personalized ads (Google AdSense) and analyze traffic.
    You can accept all cookies, accept only essential cookies, or deny non-essential cookies.
    <a href="../../pages/privacy.html">Privacy Policy</a>
  </p>
  <div id="cookie-consent-buttons">
    <button id="btn-accept-all">Accept All</button>
    <button id="btn-accept-essential">Essential Only</button>
    <button id="btn-deny">Deny</button>
  </div>
</div>

<script>
(function() {
  var consent = localStorage.getItem("cookie_consent");

  function loadAdSense() {
    if (document.querySelector('script[src*="adsbygoogle"]')) return;
    var s = document.createElement("script");
    s.async = true;
    s.src = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9738638303661485";
    s.crossOrigin = "anonymous";
    document.head.appendChild(s);
  }

  function showBanner() {
    document.getElementById("cookie-consent-banner").style.display = "block";
  }

  function hideBanner() {
    document.getElementById("cookie-consent-banner").style.display = "none";
  }

  if (consent === "all") {
    loadAdSense();
  } else if (consent === "essential" || consent === "denied") {
    // Do not load AdSense
  } else {
    // No choice made yet — show banner, do not load AdSense
    window.addEventListener("DOMContentLoaded", showBanner);
  }

  window.addEventListener("DOMContentLoaded", function() {
    document.getElementById("btn-accept-all").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "all");
      hideBanner();
      loadAdSense();
    });
    document.getElementById("btn-accept-essential").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "essential");
      hideBanner();
    });
    document.getElementById("btn-deny").addEventListener("click", function() {
      localStorage.setItem("cookie_consent", "denied");
      hideBanner();
    });
  });
})();
</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">




<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Vectoring AI
      </li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Vectoring AI</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/VectoringAI" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.youtube.com/@vectoringai" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-youtube"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">AI Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/agent.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Agent</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/rag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RAG</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/benchmark.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI Benchmark</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/milestone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI Milestones</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../pages/about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title"><strong>Sections</strong></h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#timeline-of-key-milestones" id="toc-timeline-of-key-milestones" class="nav-link" data-scroll-target="#timeline-of-key-milestones">Timeline of Key Milestones</a></li>
  <li><a href="#gpt-3-the-scale-revolution-2020" id="toc-gpt-3-the-scale-revolution-2020" class="nav-link" data-scroll-target="#gpt-3-the-scale-revolution-2020">GPT-3: The Scale Revolution (2020)</a></li>
  <li><a href="#vision-transformer-vit-transformers-conquer-vision-2020" id="toc-vision-transformer-vit-transformers-conquer-vision-2020" class="nav-link" data-scroll-target="#vision-transformer-vit-transformers-conquer-vision-2020">Vision Transformer (ViT): Transformers Conquer Vision (2020)</a></li>
  <li><a href="#alphafold2-solving-protein-folding-20202021" id="toc-alphafold2-solving-protein-folding-20202021" class="nav-link" data-scroll-target="#alphafold2-solving-protein-folding-20202021">AlphaFold2: Solving Protein Folding (2020–2021)</a></li>
  <li><a href="#dalle-and-clip-vision-meets-language-2021" id="toc-dalle-and-clip-vision-meets-language-2021" class="nav-link" data-scroll-target="#dalle-and-clip-vision-meets-language-2021">DALL·E and CLIP: Vision Meets Language (2021)</a></li>
  <li><a href="#codex-and-github-copilot-ai-writes-code-2021" id="toc-codex-and-github-copilot-ai-writes-code-2021" class="nav-link" data-scroll-target="#codex-and-github-copilot-ai-writes-code-2021">Codex and GitHub Copilot: AI Writes Code (2021)</a></li>
  <li><a href="#chatgpt-the-moment-everything-changed-november-2022" id="toc-chatgpt-the-moment-everything-changed-november-2022" class="nav-link" data-scroll-target="#chatgpt-the-moment-everything-changed-november-2022">ChatGPT: The Moment Everything Changed (November 2022)</a></li>
  <li><a href="#instructgpt-and-rlhf-aligning-ai-with-human-values-2022" id="toc-instructgpt-and-rlhf-aligning-ai-with-human-values-2022" class="nav-link" data-scroll-target="#instructgpt-and-rlhf-aligning-ai-with-human-values-2022">InstructGPT and RLHF: Aligning AI with Human Values (2022)</a></li>
  <li><a href="#chinchilla-and-scaling-laws-how-to-train-efficiently-2022" id="toc-chinchilla-and-scaling-laws-how-to-train-efficiently-2022" class="nav-link" data-scroll-target="#chinchilla-and-scaling-laws-how-to-train-efficiently-2022">Chinchilla and Scaling Laws: How to Train Efficiently (2022)</a></li>
  <li><a href="#dalle-2-and-stable-diffusion-the-generative-image-revolution-2022" id="toc-dalle-2-and-stable-diffusion-the-generative-image-revolution-2022" class="nav-link" data-scroll-target="#dalle-2-and-stable-diffusion-the-generative-image-revolution-2022">DALL·E 2 and Stable Diffusion: The Generative Image Revolution (2022)</a></li>
  <li><a href="#chain-of-thought-prompting-teaching-llms-to-reason-2022" id="toc-chain-of-thought-prompting-teaching-llms-to-reason-2022" class="nav-link" data-scroll-target="#chain-of-thought-prompting-teaching-llms-to-reason-2022">Chain-of-Thought Prompting: Teaching LLMs to Reason (2022)</a></li>
  <li><a href="#gpt-4-multimodal-intelligence-march-2023" id="toc-gpt-4-multimodal-intelligence-march-2023" class="nav-link" data-scroll-target="#gpt-4-multimodal-intelligence-march-2023">GPT-4: Multimodal Intelligence (March 2023)</a></li>
  <li><a href="#segment-anything-model-sam-foundation-model-for-vision-april-2023" id="toc-segment-anything-model-sam-foundation-model-for-vision-april-2023" class="nav-link" data-scroll-target="#segment-anything-model-sam-foundation-model-for-vision-april-2023">Segment Anything Model (SAM): Foundation Model for Vision (April 2023)</a></li>
  <li><a href="#llama-and-open-source-language-models-2023" id="toc-llama-and-open-source-language-models-2023" class="nav-link" data-scroll-target="#llama-and-open-source-language-models-2023">LLaMA and Open-Source Language Models (2023)</a></li>
  <li><a href="#generative-art-and-creative-ai-20222023" id="toc-generative-art-and-creative-ai-20222023" class="nav-link" data-scroll-target="#generative-art-and-creative-ai-20222023">Generative Art and Creative AI (2022–2023)</a></li>
  <li><a href="#microsoft-365-copilot-ai-in-enterprise-2023" id="toc-microsoft-365-copilot-ai-in-enterprise-2023" class="nav-link" data-scroll-target="#microsoft-365-copilot-ai-in-enterprise-2023">Microsoft 365 Copilot: AI in Enterprise (2023)</a></li>
  <li><a href="#multimodal-ai-and-gpt-4o-2024" id="toc-multimodal-ai-and-gpt-4o-2024" class="nav-link" data-scroll-target="#multimodal-ai-and-gpt-4o-2024">Multimodal AI and GPT-4o (2024)</a></li>
  <li><a href="#on-device-ai-and-model-efficiency-2024" id="toc-on-device-ai-and-model-efficiency-2024" class="nav-link" data-scroll-target="#on-device-ai-and-model-efficiency-2024">On-Device AI and Model Efficiency (2024)</a></li>
  <li><a href="#ai-governance-and-the-eu-ai-act-2024" id="toc-ai-governance-and-the-eu-ai-act-2024" class="nav-link" data-scroll-target="#ai-governance-and-the-eu-ai-act-2024">AI Governance and the EU AI Act (2024)</a></li>
  <li><a href="#ai-agents-the-next-frontier-2025" id="toc-ai-agents-the-next-frontier-2025" class="nav-link" data-scroll-target="#ai-agents-the-next-frontier-2025">AI Agents: The Next Frontier (2025)</a></li>
  <li><a href="#deepseek-and-the-open-reasoning-revolution-2025" id="toc-deepseek-and-the-open-reasoning-revolution-2025" class="nav-link" data-scroll-target="#deepseek-and-the-open-reasoning-revolution-2025">DeepSeek and the Open Reasoning Revolution (2025)</a></li>
  <li><a href="#text-to-video-and-the-expanding-creative-frontier-20242025" id="toc-text-to-video-and-the-expanding-creative-frontier-20242025" class="nav-link" data-scroll-target="#text-to-video-and-the-expanding-creative-frontier-20242025">Text-to-Video and the Expanding Creative Frontier (2024–2025)</a></li>
  <li><a href="#the-20202025-transformation-at-a-glance" id="toc-the-20202025-transformation-at-a-glance" class="nav-link" data-scroll-target="#the-20202025-transformation-at-a-glance">The 2020–2025 Transformation at a Glance</a></li>
  <li><a href="#video-20202025-ai-milestones-chatgpt-moments-generative-ai-agentic-ai" id="toc-video-20202025-ai-milestones-chatgpt-moments-generative-ai-agentic-ai" class="nav-link" data-scroll-target="#video-20202025-ai-milestones-chatgpt-moments-generative-ai-agentic-ai">Video: 2020–2025 AI Milestones — ChatGPT Moments, Generative AI &amp; Agentic AI</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#read-more" id="toc-read-more" class="nav-link" data-scroll-target="#read-more">Read More</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2020–2025 AI Milestones</h1>
<p class="subtitle lead">ChatGPT Moments, Generative AI &amp; Agentic AI — how large language models, diffusion models, and autonomous agents reshaped civilization</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 24, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Keywords:</strong> AI history, 2020s AI, GPT-3, GPT-4, ChatGPT, OpenAI, large language models, generative AI, DALL-E, Stable Diffusion, Midjourney, diffusion models, AlphaFold2, protein folding, CLIP, vision transformer, ViT, InstructGPT, RLHF, reinforcement learning from human feedback, Chinchilla, scaling laws, chain-of-thought prompting, LLaMA, Llama 2, Meta AI, Segment Anything Model, SAM, GitHub Copilot, Codex, AI agents, agentic AI, multimodal AI, GPT-4o, on-device AI, AI governance, EU AI Act, text-to-video, Sora, DeepSeek, open-source LLMs, AI safety, alignment, reasoning models</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../..\images/milestone/2020-2025-ai-milestones-300px.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="300"></p>
</figure>
</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The first half of the 2020s will be remembered as the era when <strong>artificial intelligence left the lab and entered everyday life</strong>. In just five years, AI progressed from a powerful but largely invisible technology to a cultural force that reshaped how billions of people work, create, learn, and communicate.</p>
<p>The period opened with a dramatic scaling experiment: in June 2020, OpenAI released <strong>GPT-3</strong>, a language model with 175 billion parameters that could write essays, code, and poetry from a simple text prompt. The era of few-shot learning had arrived — but the real earthquake came two years later. On November 30, 2022, OpenAI launched <strong>ChatGPT</strong>, a conversational interface to its large language models. It reached 100 million users in two months — the fastest consumer adoption in history — and ignited a generative AI revolution that swept through every industry on Earth.</p>
<p>Parallel breakthroughs in <strong>image generation</strong> transformed creativity itself. <strong>DALL·E</strong> (2021), <strong>Stable Diffusion</strong> (2022), and <strong>Midjourney</strong> became cultural phenomena, enabling anyone to generate photorealistic images from text descriptions. In science, <strong>AlphaFold2</strong> solved the 50-year-old protein folding problem, predicting the structures of virtually all known proteins and winning its creators the 2024 Nobel Prize in Chemistry.</p>
<p>The march continued with <strong>GPT-4</strong> (2023), which demonstrated multimodal reasoning across text and images; <strong>LLaMA</strong> and its successors, which democratized large language models through open weights; and the <strong>Segment Anything Model</strong>, which did for computer vision what BERT had done for language. By 2024, <strong>multimodal assistants</strong> could see, hear, and speak; <strong>on-device AI</strong> brought language models to smartphones and laptops; and governments worldwide began crafting AI governance frameworks, including the landmark <strong>EU AI Act</strong>.</p>
<p>By 2025, the frontier had shifted to <strong>agentic AI</strong> — systems that don’t just answer questions but plan, reason, use tools, and take autonomous actions. The AI agent era had begun, built atop everything that came before: transformers, scaling laws, RLHF alignment, and the hard-won lessons of deploying AI at planetary scale.</p>
<p>This article traces the defining milestones of 2020–2025 — from GPT-3’s few-shot learning revelation, through the ChatGPT moment that changed everything, to the rise of generative AI and the dawn of agentic systems.</p>
</section>
<section id="timeline-of-key-milestones" class="level2">
<h2 class="anchored" data-anchor-id="timeline-of-key-milestones">Timeline of Key Milestones</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">%%{init: {'theme': 'base', 'themeVariables': {'fontSize': '14px'}}}%%
timeline
    title 2020–2025 AI Milestones — ChatGPT Moments, Generative AI and Agentic AI
    2020 : GPT-3 — 175 billion parameters, few-shot learning
         : Vision Transformer (ViT) — applies transformers to image classification
         : AlphaFold2 wins CASP14 — solves protein folding
    2021 : DALL·E and CLIP — text-to-image generation and vision-language alignment
         : Codex and GitHub Copilot — AI-powered code generation
         : AlphaFold Protein Structure Database launched — 200M+ protein structures
    2022 : ChatGPT launched — 100M users in two months
         : InstructGPT and RLHF — aligning LLMs with human preferences
         : Chinchilla — optimal compute-data scaling laws
         : DALL·E 2 and Stable Diffusion — photorealistic image generation goes mainstream
         : Chain-of-thought prompting — teaching LLMs to reason step by step
    2023 : GPT-4 — multimodal reasoning across text and images
         : Segment Anything Model (SAM) — foundation model for computer vision
         : LLaMA and Llama 2 — Meta open-weights revolution
         : Midjourney V5 and DALL·E 3 — generative art reaches new heights
         : Microsoft 365 Copilot — AI embedded in enterprise productivity
    2024 : GPT-4o — omni-modal real-time AI assistant
         : AlphaFold3 — predicts structures of protein-DNA-RNA complexes
         : On-device AI — language models on smartphones and laptops
         : EU AI Act enters force — first comprehensive AI regulation
         : Nobel Prize in Chemistry for AlphaFold creators
    2025 : AI agents — planning, tool use, and autonomous multi-step actions
         : DeepSeek and open reasoning models challenge frontier labs
         : Text-to-video generation — Sora and the next creative frontier
         : AI governance frameworks expand worldwide
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="gpt-3-the-scale-revolution-2020" class="level2">
<h2 class="anchored" data-anchor-id="gpt-3-the-scale-revolution-2020">GPT-3: The Scale Revolution (2020)</h2>
<p>In June 2020, <strong>OpenAI</strong> released <strong>GPT-3</strong> — a language model with <strong>175 billion parameters</strong> trained on a massive corpus of internet text. GPT-3 demonstrated a stunning capability that its predecessors only hinted at: <strong>few-shot learning</strong>. Given just a few examples in a text prompt, it could translate languages, write code, compose poetry, generate business emails, and answer factual questions — all without any task-specific fine-tuning.</p>
<p>The jump from GPT-2’s 1.5 billion parameters to GPT-3’s 175 billion was not merely quantitative. It crossed a threshold where the model exhibited <strong>emergent capabilities</strong> — behaviors that appeared only at sufficient scale. GPT-3 could perform arithmetic, write SQL queries, and even generate functional code, despite never being explicitly trained for these tasks.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Released</strong></td>
<td>June 2020</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>OpenAI</td>
</tr>
<tr class="odd">
<td><strong>Parameters</strong></td>
<td>175 billion (116× larger than GPT-2)</td>
</tr>
<tr class="even">
<td><strong>Training data</strong></td>
<td>570 GB of filtered text (Common Crawl, WebText2, Books, Wikipedia)</td>
</tr>
<tr class="odd">
<td><strong>Training cost</strong></td>
<td>Estimated $4.6 million in compute</td>
</tr>
<tr class="even">
<td><strong>Key capability</strong></td>
<td>Few-shot learning — task performance from prompt examples alone</td>
</tr>
<tr class="odd">
<td><strong>Access model</strong></td>
<td>API-only (no public weights released)</td>
</tr>
<tr class="even">
<td><strong>Significance</strong></td>
<td>Demonstrated that scale alone could unlock emergent capabilities</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“One of the things that was most surprising about GPT-3 is that it can do things it was never trained to do.” — Sam Altman, CEO of OpenAI</p>
</blockquote>
<p>GPT-3 also ignited a debate about the nature of intelligence. Critics argued it was a sophisticated pattern matcher with no genuine understanding; proponents countered that its ability to generalize across tasks suggested something beyond mere memorization. Regardless of the philosophical disputes, GPT-3 proved that massive scale and simple next-token prediction could produce remarkably versatile systems — and set the stage for the ChatGPT moment that would come two years later.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["GPT-1&lt;br/&gt;117M params&lt;br/&gt;(2018)"] --&gt; B["GPT-2&lt;br/&gt;1.5B params&lt;br/&gt;(2019)"]
    B --&gt; C["GPT-3&lt;br/&gt;175B params&lt;br/&gt;(2020)"]
    C --&gt; D["InstructGPT&lt;br/&gt;RLHF-aligned&lt;br/&gt;(2022)"]
    D --&gt; E["ChatGPT&lt;br/&gt;Conversational UI&lt;br/&gt;(Nov 2022)"]
    E --&gt; F["GPT-4&lt;br/&gt;Multimodal&lt;br/&gt;(2023)"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#2980b9,color:#fff,stroke:#333
    style C fill:#e74c3c,color:#fff,stroke:#333
    style D fill:#27ae60,color:#fff,stroke:#333
    style E fill:#f39c12,color:#fff,stroke:#333
    style F fill:#8e44ad,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="vision-transformer-vit-transformers-conquer-vision-2020" class="level2">
<h2 class="anchored" data-anchor-id="vision-transformer-vit-transformers-conquer-vision-2020">Vision Transformer (ViT): Transformers Conquer Vision (2020)</h2>
<p>In October 2020, researchers at Google Brain published <strong>“An Image is Worth 16×16 Words”</strong>, introducing the <strong>Vision Transformer (ViT)</strong>. The paper demonstrated that a standard transformer architecture — originally designed for language — could achieve state-of-the-art image classification when applied directly to sequences of image patches, without any convolutional layers.</p>
<p>ViT divided each image into fixed-size patches (typically 16×16 pixels), flattened them into vectors, and processed the resulting sequence using a standard transformer encoder with self-attention. When pretrained on large datasets (JFT-300M), ViT outperformed the best convolutional networks on ImageNet while requiring substantially less computational budget to train.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>October 2020</td>
</tr>
<tr class="even">
<td><strong>Authors</strong></td>
<td>Alexey Dosovitskiy et al.&nbsp;(Google Brain)</td>
</tr>
<tr class="odd">
<td><strong>Architecture</strong></td>
<td>Standard transformer encoder applied to 16×16 image patches</td>
</tr>
<tr class="even">
<td><strong>Key result</strong></td>
<td>Surpassed state-of-the-art CNNs on ImageNet when pretrained at scale</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Unified vision and language under a single transformer architecture</td>
</tr>
<tr class="even">
<td><strong>Follow-ups</strong></td>
<td>DeiT, Swin Transformer, BEiT, DINO — transformer-based vision became dominant</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“An image is worth 16×16 words” — the paper’s title captured the elegant simplicity of treating image patches as tokens.</p>
</blockquote>
<p>ViT’s success had far-reaching consequences. It demonstrated that the transformer architecture was not specific to language but was a <strong>general-purpose sequence processor</strong>. This insight accelerated research into multimodal models — systems that could process text, images, audio, and video within a unified transformer framework — and paved the way for CLIP, DALL·E, and the multimodal assistants that emerged in 2023–2024.</p>
</section>
<section id="alphafold2-solving-protein-folding-20202021" class="level2">
<h2 class="anchored" data-anchor-id="alphafold2-solving-protein-folding-20202021">AlphaFold2: Solving Protein Folding (2020–2021)</h2>
<p>In November 2020, <strong>DeepMind’s AlphaFold2</strong> achieved a breakthrough that scientists had pursued for 50 years: accurately predicting the three-dimensional structure of proteins from their amino acid sequences. At the <strong>CASP14</strong> (Critical Assessment of protein Structure Prediction) competition, AlphaFold2 achieved a median GDT score of <strong>92.4 out of 100</strong> — a level of accuracy comparable to experimental techniques like X-ray crystallography — and made the best prediction for 88 out of 97 targets.</p>
<p>In July 2021, DeepMind and EMBL-EBI launched the <strong>AlphaFold Protein Structure Database</strong>, initially containing predictions for the human proteome and 20 model organisms. By July 2022, the database expanded to cover <strong>over 200 million protein structures</strong> — virtually every known protein across all life forms.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>CASP14 results</strong></td>
<td>November 2020</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>DeepMind (Google / Alphabet)</td>
</tr>
<tr class="odd">
<td><strong>Architecture</strong></td>
<td>Evoformer + structure module, end-to-end differentiable</td>
</tr>
<tr class="even">
<td><strong>CASP14 median GDT</strong></td>
<td>92.4 / 100 (comparable to experimental methods)</td>
</tr>
<tr class="odd">
<td><strong>Database launched</strong></td>
<td>July 2021 — expanded to 200M+ structures by July 2022</td>
</tr>
<tr class="even">
<td><strong>Nobel Prize</strong></td>
<td>2024 Nobel Prize in Chemistry — Demis Hassabis and John Jumper</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Solved a 50-year grand challenge in biology</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Nobel laureate Venki Ramakrishnan called AlphaFold2 “a stunning advance on the protein folding problem… It has occurred decades before many people in the field would have predicted.”</p>
</blockquote>
<p>AlphaFold2’s impact on biology and medicine has been transformational. Researchers worldwide use it to understand disease mechanisms, design new drugs, and engineer novel proteins. In 2024, AlphaFold’s creators — <strong>Demis Hassabis</strong> and <strong>John Jumper</strong> — shared the Nobel Prize in Chemistry for their work on protein structure prediction, alongside David Baker for computational protein design. <strong>AlphaFold3</strong> (2024) extended the approach to predict structures of protein complexes with DNA, RNA, and other molecules.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["Amino Acid&lt;br/&gt;Sequence Input"] --&gt; B["Multiple Sequence&lt;br/&gt;Alignment (MSA)"]
    B --&gt; C["Evoformer&lt;br/&gt;(Attention-based)"]
    C --&gt; D["Structure&lt;br/&gt;Prediction Module"]
    D --&gt; E["3D Protein&lt;br/&gt;Structure Output"]
    E --&gt; F["CASP14: 92.4 GDT&lt;br/&gt;(Comparable to&lt;br/&gt;X-ray crystallography)"]
    F --&gt; G["200M+ Protein&lt;br/&gt;Structures in Database"]
    G --&gt; H["2024 Nobel Prize&lt;br/&gt;in Chemistry"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#2980b9,color:#fff,stroke:#333
    style C fill:#e74c3c,color:#fff,stroke:#333
    style D fill:#27ae60,color:#fff,stroke:#333
    style E fill:#f39c12,color:#fff,stroke:#333
    style F fill:#8e44ad,color:#fff,stroke:#333
    style G fill:#1a5276,color:#fff,stroke:#333
    style H fill:#e67e22,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="dalle-and-clip-vision-meets-language-2021" class="level2">
<h2 class="anchored" data-anchor-id="dalle-and-clip-vision-meets-language-2021">DALL·E and CLIP: Vision Meets Language (2021)</h2>
<p>In January 2021, <strong>OpenAI</strong> unveiled two groundbreaking systems that bridged the gap between vision and language: <strong>DALL·E</strong>, a model that generated images from text descriptions, and <strong>CLIP</strong> (Contrastive Language–Image Pre-training), which learned to connect images and text in a shared embedding space.</p>
<p><strong>CLIP</strong> was trained on 400 million image-text pairs scraped from the internet, learning to match images with their corresponding text descriptions using contrastive learning. The result was a visual system that could classify images using natural language descriptions — including categories it had never seen during training (zero-shot classification).</p>
<p><strong>DALL·E</strong> (a portmanteau of Salvador Dalí and WALL·E) was a 12-billion parameter version of GPT-3, modified to generate images from text prompts. It could produce images of “an armchair in the shape of an avocado” or “a snail made of harp strings” — demonstrating a compositional understanding of language and visual concepts that stunned researchers.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Announced</strong></td>
<td>January 2021</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>OpenAI</td>
</tr>
<tr class="odd">
<td><strong>CLIP</strong></td>
<td>Contrastive learning on 400M image-text pairs; zero-shot image classification</td>
</tr>
<tr class="even">
<td><strong>DALL·E</strong></td>
<td>12B parameter GPT-3 variant; text-to-image generation</td>
</tr>
<tr class="odd">
<td><strong>Key insight</strong></td>
<td>Vision and language can be learned jointly in a shared representation space</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Foundation for DALL·E 2, Stable Diffusion, Midjourney, and multimodal AI</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“CLIP effectively generalizes to virtually any visual classification task, merely by describing the classes in natural language.” — OpenAI Research Blog</p>
</blockquote>
<p>CLIP’s vision-language alignment became the backbone of the generative image revolution that followed. <strong>Stable Diffusion</strong> used CLIP’s text encoder to steer its diffusion process; <strong>DALL·E 2</strong> and <strong>DALL·E 3</strong> built upon CLIP’s multimodal understanding. The insight that vision and language could be unified in a single representation space became one of the defining ideas of the era.</p>
</section>
<section id="codex-and-github-copilot-ai-writes-code-2021" class="level2">
<h2 class="anchored" data-anchor-id="codex-and-github-copilot-ai-writes-code-2021">Codex and GitHub Copilot: AI Writes Code (2021)</h2>
<p>In August 2021, <strong>OpenAI</strong> released <strong>Codex</strong>, a GPT-3 descendant fine-tuned on publicly available code from GitHub. Codex could translate natural language instructions into working code across dozens of programming languages. In June 2021, Microsoft and OpenAI launched <strong>GitHub Copilot</strong> — an AI pair-programming tool powered by Codex that suggested code completions directly inside the developer’s editor.</p>
<p>Copilot was among the first AI systems to be adopted at massive scale in professional workflows. Within two years, it had millions of users and was generating a significant fraction of the code written by its adopters. Developers described it as transformative — not replacing programmers but dramatically accelerating their work.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Codex released</strong></td>
<td>August 2021</td>
</tr>
<tr class="even">
<td><strong>GitHub Copilot launched</strong></td>
<td>June 2021 (technical preview), general availability June 2022</td>
</tr>
<tr class="odd">
<td><strong>Developer</strong></td>
<td>OpenAI (Codex), GitHub / Microsoft (Copilot)</td>
</tr>
<tr class="even">
<td><strong>Based on</strong></td>
<td>GPT-3, fine-tuned on public GitHub code</td>
</tr>
<tr class="odd">
<td><strong>Languages</strong></td>
<td>Python, JavaScript, TypeScript, Go, Ruby, and dozens more</td>
</tr>
<tr class="even">
<td><strong>Significance</strong></td>
<td>First widely adopted AI tool for professional software development</td>
</tr>
<tr class="odd">
<td><strong>Impact</strong></td>
<td>Millions of developers; accelerated coding velocity by 30–55% in studies</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“Copilot writes the boring code so I can focus on the interesting code.” — common developer sentiment, 2022</p>
</blockquote>
<p>GitHub Copilot demonstrated that LLMs could serve as practical, everyday productivity tools — not just research curiosities. Its success paved the way for <strong>Microsoft 365 Copilot</strong> (2023), which brought the same paradigm to documents, spreadsheets, presentations, and email, embedding AI assistance into the core of enterprise productivity.</p>
</section>
<section id="chatgpt-the-moment-everything-changed-november-2022" class="level2">
<h2 class="anchored" data-anchor-id="chatgpt-the-moment-everything-changed-november-2022">ChatGPT: The Moment Everything Changed (November 2022)</h2>
<p>On <strong>November 30, 2022</strong>, OpenAI released <strong>ChatGPT</strong> — a conversational interface to its GPT-3.5 language model, fine-tuned using <strong>Reinforcement Learning from Human Feedback (RLHF)</strong> to be helpful, harmless, and honest. Within five days, it had one million users. Within two months, it reached <strong>100 million monthly active users</strong> — making it the fastest-growing consumer application in history.</p>
<p>ChatGPT did not introduce fundamentally new AI capabilities. GPT-3 already existed; RLHF had been published in the <strong>InstructGPT</strong> paper earlier in 2022. What ChatGPT achieved was something more profound: it <strong>made AI accessible to everyone</strong>. The conversational interface — simple, free, and requiring no technical expertise — invited hundreds of millions of people to interact directly with a large language model for the first time.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Launched</strong></td>
<td>November 30, 2022</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>OpenAI</td>
</tr>
<tr class="odd">
<td><strong>Underlying model</strong></td>
<td>GPT-3.5, fine-tuned with RLHF</td>
</tr>
<tr class="even">
<td><strong>1 million users</strong></td>
<td>Within 5 days</td>
</tr>
<tr class="odd">
<td><strong>100 million users</strong></td>
<td>Within 2 months (fastest-growing consumer app ever)</td>
</tr>
<tr class="even">
<td><strong>ChatGPT Plus</strong></td>
<td>Launched February 2023 ($20/month)</td>
</tr>
<tr class="odd">
<td><strong>Key innovation</strong></td>
<td>Conversational UI + RLHF alignment made LLMs accessible to everyone</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Ignited the generative AI boom; triggered industry-wide AI arms race</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>Kevin Roose of <em>The New York Times</em> called ChatGPT “the best artificial intelligence chatbot ever released to the general public.”</p>
</blockquote>
<p>The ripple effects were immediate and seismic. Google declared a “code red” and rushed to launch its own chatbot, <strong>Bard</strong> (later Gemini). Microsoft invested $10 billion in OpenAI and integrated GPT-4 into Bing. Every major tech company pivoted to generative AI. Startups raised billions. Universities debated how to handle AI-generated assignments. And for the first time in history, hundreds of millions of ordinary people experienced the power — and the limitations — of conversational AI directly.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["GPT-3&lt;br/&gt;(June 2020)"] --&gt; B["InstructGPT + RLHF&lt;br/&gt;(March 2022)"]
    B --&gt; C["ChatGPT&lt;br/&gt;(Nov 30, 2022)"]
    C --&gt; D["100M Users&lt;br/&gt;in 2 Months"]
    D --&gt; E["Google Bard&lt;br/&gt;Microsoft Bing Chat&lt;br/&gt;Industry AI Arms Race"]
    C --&gt; F["ChatGPT Plus&lt;br/&gt;(Feb 2023)"]
    F --&gt; G["GPT-4 Integration&lt;br/&gt;(March 2023)"]
    G --&gt; H["Plugins, Browsing,&lt;br/&gt;Code Interpreter"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#27ae60,color:#fff,stroke:#333
    style C fill:#e74c3c,color:#fff,stroke:#333
    style D fill:#f39c12,color:#fff,stroke:#333
    style E fill:#8e44ad,color:#fff,stroke:#333
    style F fill:#1a5276,color:#fff,stroke:#333
    style G fill:#2980b9,color:#fff,stroke:#333
    style H fill:#e67e22,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="instructgpt-and-rlhf-aligning-ai-with-human-values-2022" class="level2">
<h2 class="anchored" data-anchor-id="instructgpt-and-rlhf-aligning-ai-with-human-values-2022">InstructGPT and RLHF: Aligning AI with Human Values (2022)</h2>
<p>In March 2022, OpenAI published the <strong>InstructGPT</strong> paper, describing how they used <strong>Reinforcement Learning from Human Feedback (RLHF)</strong> to align language models with human intentions. The key insight was simple but powerful: instead of training only on next-token prediction, you could fine-tune a model to follow instructions, be truthful, and avoid harmful outputs — by using human preferences as a training signal.</p>
<p>The process involved three steps: (1) collect human demonstrations of ideal responses and fine-tune the model via supervised learning; (2) have human raters rank multiple model outputs to train a <strong>reward model</strong>; (3) use the reward model to fine-tune the language model via <strong>Proximal Policy Optimization (PPO)</strong>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>March 2022</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>OpenAI</td>
</tr>
<tr class="odd">
<td><strong>Technique</strong></td>
<td>RLHF — Reinforcement Learning from Human Feedback</td>
</tr>
<tr class="even">
<td><strong>Steps</strong></td>
<td>Supervised fine-tuning → Reward model training → PPO optimization</td>
</tr>
<tr class="odd">
<td><strong>Applied to</strong></td>
<td>GPT-3 (1.3B parameters) initially; later GPT-3.5 and GPT-4</td>
</tr>
<tr class="even">
<td><strong>Key result</strong></td>
<td>A 1.3B InstructGPT was preferred over the 175B GPT-3 by human raters</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Established RLHF as the standard method for aligning LLMs</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“Our 1.3 billion parameter InstructGPT model outputs are preferred to outputs of the 175 billion parameter GPT-3, despite having 100× fewer parameters.” — Ouyang et al.&nbsp;(2022)</p>
</blockquote>
<p>RLHF became the default alignment technique across the industry. Google used it for Gemini, Anthropic refined it into <strong>RLAIF</strong> (RL from AI Feedback) and <strong>Constitutional AI</strong>, and Meta applied it to Llama. The InstructGPT paper established that <strong>alignment is not just about making models larger — it’s about making them better at following human intent</strong> — a lesson that underpins the entire modern AI stack.</p>
</section>
<section id="chinchilla-and-scaling-laws-how-to-train-efficiently-2022" class="level2">
<h2 class="anchored" data-anchor-id="chinchilla-and-scaling-laws-how-to-train-efficiently-2022">Chinchilla and Scaling Laws: How to Train Efficiently (2022)</h2>
<p>In March 2022, <strong>DeepMind</strong> published <strong>“Training Compute-Optimal Large Language Models”</strong>, introducing the <strong>Chinchilla</strong> model. The paper challenged the prevailing wisdom on scaling — demonstrating that most large language models were significantly <strong>undertrained</strong> relative to their size.</p>
<p>The key finding: for a given compute budget, the optimal strategy is to scale model size and training data <strong>equally</strong>. A 70-billion parameter model trained on 1.4 trillion tokens (<strong>Chinchilla</strong>) outperformed the 280-billion parameter <strong>Gopher</strong> trained on 300 billion tokens — despite using four times fewer parameters.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>March 2022</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>DeepMind</td>
</tr>
<tr class="odd">
<td><strong>Model</strong></td>
<td>Chinchilla (70B parameters, 1.4T training tokens)</td>
</tr>
<tr class="even">
<td><strong>Key finding</strong></td>
<td>Models should be trained on ~20 tokens per parameter for compute-optimality</td>
</tr>
<tr class="odd">
<td><strong>Result</strong></td>
<td>Chinchilla (70B) outperformed Gopher (280B) on most benchmarks</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Shifted industry focus from parameter count to data quality and quantity</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“For every doubling of model size, the number of training tokens should also be doubled.” — Hoffmann et al.&nbsp;(2022)</p>
</blockquote>
<p>Chinchilla’s scaling laws reshaped how every lab trained large models. Meta’s <strong>LLaMA</strong> (2023) explicitly followed Chinchilla-optimal ratios, training a 65B parameter model on 1.4 trillion tokens. The lesson propagated industry-wide: <strong>more data, not just more parameters</strong>, was the path to better models.</p>
</section>
<section id="dalle-2-and-stable-diffusion-the-generative-image-revolution-2022" class="level2">
<h2 class="anchored" data-anchor-id="dalle-2-and-stable-diffusion-the-generative-image-revolution-2022">DALL·E 2 and Stable Diffusion: The Generative Image Revolution (2022)</h2>
<p>In April 2022, OpenAI released <strong>DALL·E 2</strong>, which used a diffusion-based approach (replacing the original DALL·E’s autoregressive method) to generate photorealistic images from text prompts at much higher resolution and fidelity. Then in August 2022, <strong>Stability AI</strong> released <strong>Stable Diffusion</strong> — an open-source latent diffusion model that could run on consumer GPUs.</p>
<p>Stable Diffusion democratized image generation. Unlike DALL·E 2, which was available only through an API, Stable Diffusion’s weights and code were publicly available. Anyone with a modest GPU could generate, modify, and fine-tune their own image generation models. Within weeks, a vibrant ecosystem of tools, extensions, and communities emerged.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>DALL·E 2 released</strong></td>
<td>April 2022</td>
</tr>
<tr class="even">
<td><strong>Stable Diffusion released</strong></td>
<td>August 2022</td>
</tr>
<tr class="odd">
<td><strong>SD architecture</strong></td>
<td>Latent Diffusion Model (VAE + U-Net + CLIP text encoder)</td>
</tr>
<tr class="even">
<td><strong>SD parameters</strong></td>
<td>~860M (U-Net) + 123M (text encoder)</td>
</tr>
<tr class="odd">
<td><strong>SD training cost</strong></td>
<td>~$600,000 on 256 NVIDIA A100 GPUs</td>
</tr>
<tr class="even">
<td><strong>Key innovation</strong></td>
<td>Diffusion in latent space — high quality at lower compute cost</td>
</tr>
<tr class="odd">
<td><strong>Impact</strong></td>
<td>Open-source image generation; ran on consumer hardware</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“Stable Diffusion marked the moment when AI image generation left the laboratory and entered the hands of millions.” — <em>MIT Technology Review</em></p>
</blockquote>
<p>The generative image revolution raised profound questions about copyright, consent, and the future of creative work. Artists protested that their styles were being replicated without permission. Legal battles ensued — Getty Images sued Stability AI; artists sued both Stability AI and Midjourney. Meanwhile, the technology continued to advance: <strong>Midjourney V5</strong> (2023) produced images indistinguishable from photographs, and <strong>DALL·E 3</strong> (October 2023) was integrated directly into ChatGPT.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["DALL·E 1&lt;br/&gt;(Jan 2021)&lt;br/&gt;Autoregressive"] --&gt; B["DALL·E 2&lt;br/&gt;(Apr 2022)&lt;br/&gt;Diffusion"]
    C["Latent Diffusion&lt;br/&gt;(LMU Munich, 2021)"] --&gt; D["Stable Diffusion&lt;br/&gt;(Aug 2022)&lt;br/&gt;Open Source"]
    B --&gt; E["DALL·E 3&lt;br/&gt;(Oct 2023)&lt;br/&gt;ChatGPT Integration"]
    D --&gt; F["SD XL · SD 3&lt;br/&gt;Community Ecosystem"]
    G["Midjourney&lt;br/&gt;(2022–2023)"] --&gt; H["Generative AI&lt;br/&gt;Cultural Phenomenon"]
    E --&gt; H
    F --&gt; H

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#2980b9,color:#fff,stroke:#333
    style C fill:#27ae60,color:#fff,stroke:#333
    style D fill:#e74c3c,color:#fff,stroke:#333
    style E fill:#8e44ad,color:#fff,stroke:#333
    style F fill:#f39c12,color:#fff,stroke:#333
    style G fill:#1a5276,color:#fff,stroke:#333
    style H fill:#e67e22,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="chain-of-thought-prompting-teaching-llms-to-reason-2022" class="level2">
<h2 class="anchored" data-anchor-id="chain-of-thought-prompting-teaching-llms-to-reason-2022">Chain-of-Thought Prompting: Teaching LLMs to Reason (2022)</h2>
<p>In January 2022, <strong>Jason Wei</strong> and colleagues at Google Brain published a paper demonstrating that adding the phrase “Let’s think step by step” to a prompt — or providing worked examples with explicit intermediate reasoning — could dramatically improve LLM performance on math, logic, and multi-step reasoning tasks. This technique became known as <strong>chain-of-thought (CoT) prompting</strong>.</p>
<p>The insight was deceptively simple: LLMs trained on next-token prediction had learned to reason, but only when the reasoning process was made explicit in the output. By prompting the model to “show its work,” performance on arithmetic, commonsense reasoning, and symbolic manipulation improved by up to <strong>60%</strong> on some benchmarks.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Published</strong></td>
<td>January 2022 (Wei et al.)</td>
</tr>
<tr class="even">
<td><strong>Developers</strong></td>
<td>Google Brain</td>
</tr>
<tr class="odd">
<td><strong>Technique</strong></td>
<td>Include reasoning steps in few-shot examples or instruct “think step by step”</td>
</tr>
<tr class="even">
<td><strong>Key result</strong></td>
<td>GSM8K math accuracy improved from ~18% to ~57% on PaLM 540B</td>
</tr>
<tr class="odd">
<td><strong>Variants</strong></td>
<td>Zero-shot CoT, self-consistency, tree-of-thought, chain-of-thought distillation</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Foundation for reasoning models (o1, o3) and agentic workflows</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“Chain-of-thought prompting allows large language models to decompose multi-step problems into intermediate steps, significantly improving reasoning.” — Wei et al.&nbsp;(2022)</p>
</blockquote>
<p>Chain-of-thought prompting was more than a prompt engineering trick. It revealed that <strong>reasoning is an emergent capability of scale</strong> — appearing only in sufficiently large models — and it laid the conceptual foundation for the <strong>reasoning models</strong> that emerged in 2024–2025, including OpenAI’s <strong>o1</strong> and <strong>o3</strong> series, which internalized chain-of-thought as a core inference mechanism.</p>
</section>
<section id="gpt-4-multimodal-intelligence-march-2023" class="level2">
<h2 class="anchored" data-anchor-id="gpt-4-multimodal-intelligence-march-2023">GPT-4: Multimodal Intelligence (March 2023)</h2>
<p>On <strong>March 14, 2023</strong>, OpenAI released <strong>GPT-4</strong> — its most capable large language model at the time. GPT-4 was the first commercially deployed model to accept both <strong>text and image inputs</strong> (multimodal), producing text outputs that demonstrated markedly improved reasoning, factuality, and instruction-following compared to its predecessors.</p>
<p>GPT-4 passed the bar exam in the 90th percentile, scored in the 99th percentile on the GRE verbal section, and demonstrated substantial improvements on coding benchmarks. Its multimodal capability allowed users to upload images and ask questions about them — a preview of the visual reasoning that would become central to AI assistants.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Released</strong></td>
<td>March 14, 2023</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>OpenAI</td>
</tr>
<tr class="odd">
<td><strong>Modalities</strong></td>
<td>Text input + image input → text output</td>
</tr>
<tr class="even">
<td><strong>Bar exam performance</strong></td>
<td>90th percentile (vs.&nbsp;GPT-3.5’s 10th percentile)</td>
</tr>
<tr class="odd">
<td><strong>GRE verbal</strong></td>
<td>99th percentile</td>
</tr>
<tr class="even">
<td><strong>Context window</strong></td>
<td>8K and 32K token variants</td>
</tr>
<tr class="odd">
<td><strong>Follow-ups</strong></td>
<td>GPT-4 Turbo (Nov 2023), GPT-4o (May 2024), GPT-4o mini (Jul 2024)</td>
</tr>
<tr class="even">
<td><strong>Significance</strong></td>
<td>First commercially deployed multimodal LLM at scale</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“GPT-4 is more reliable, creative, and able to handle much more nuanced instructions than GPT-3.5.” — OpenAI Technical Report</p>
</blockquote>
<p>GPT-4 was quickly integrated into ChatGPT Plus, Bing Chat (now Microsoft Copilot), and hundreds of enterprise applications. It validated the bet that scaling plus RLHF alignment could produce models with genuine utility across law, medicine, coding, education, and creative work.</p>
</section>
<section id="segment-anything-model-sam-foundation-model-for-vision-april-2023" class="level2">
<h2 class="anchored" data-anchor-id="segment-anything-model-sam-foundation-model-for-vision-april-2023">Segment Anything Model (SAM): Foundation Model for Vision (April 2023)</h2>
<p>In April 2023, <strong>Meta AI</strong> released the <strong>Segment Anything Model (SAM)</strong> alongside the <strong>SA-1B dataset</strong> — the largest segmentation dataset ever created, containing over 1 billion masks on 11 million images. SAM could segment any object in any image, prompted by a point, a bounding box, or a text description — without being trained on that specific object category.</p>
<p>SAM did for computer vision what GPT-3 did for language: it demonstrated that a single, large foundation model could generalize across virtually any visual segmentation task. It was a <strong>zero-shot, promptable</strong> vision model — a paradigm shift from task-specific models that required custom training for each new class of objects.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Released</strong></td>
<td>April 2023</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>Meta AI Research (FAIR)</td>
</tr>
<tr class="odd">
<td><strong>Dataset</strong></td>
<td>SA-1B — 1.1 billion masks on 11 million images</td>
</tr>
<tr class="even">
<td><strong>Architecture</strong></td>
<td>Image encoder (ViT-H) + prompt encoder + mask decoder</td>
</tr>
<tr class="odd">
<td><strong>Key capability</strong></td>
<td>Zero-shot segmentation of any object from points, boxes, or text</td>
</tr>
<tr class="even">
<td><strong>Follow-up</strong></td>
<td>SAM 2 (2024) extended to video segmentation</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Foundation model paradigm applied to computer vision segmentation</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“SAM is to image segmentation what GPT-3 was to text generation — a demonstration that foundation models can generalize across an entire domain.” — <em>Meta AI Blog</em></p>
</blockquote>
<p>SAM accelerated research in autonomous driving, medical imaging, robotics, augmented reality, and video editing. Its release as open source ensured rapid adoption and inspired dozens of follow-up projects that extended the approach to 3D, video, and domain-specific applications.</p>
</section>
<section id="llama-and-open-source-language-models-2023" class="level2">
<h2 class="anchored" data-anchor-id="llama-and-open-source-language-models-2023">LLaMA and Open-Source Language Models (2023)</h2>
<p>In February 2023, <strong>Meta AI</strong> released <strong>LLaMA</strong> (Large Language Model Meta AI) — a family of language models ranging from 7B to 65B parameters. Unlike GPT-4, LLaMA’s weights were made available to the research community (and soon leaked publicly), igniting an <strong>open-source AI revolution</strong>.</p>
<p>LLaMA followed <strong>Chinchilla-optimal scaling</strong>: the 65B model was trained on 1.4 trillion tokens — far more data per parameter than previous models. The result was a 65B model that matched or exceeded the performance of much larger proprietary models on many benchmarks. In July 2023, Meta released <strong>Llama 2</strong> with a commercial license, followed by <strong>Llama 3</strong> in April 2024 — each iteration narrowing the gap with frontier proprietary models.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LLaMA released</strong></td>
<td>February 2023</td>
</tr>
<tr class="even">
<td><strong>Llama 2 released</strong></td>
<td>July 2023 (with commercial license)</td>
</tr>
<tr class="odd">
<td><strong>Llama 3 released</strong></td>
<td>April 2024 (8B and 70B), December 2024 (405B)</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>Meta AI</td>
</tr>
<tr class="odd">
<td><strong>LLaMA sizes</strong></td>
<td>7B, 13B, 33B, 65B parameters</td>
</tr>
<tr class="even">
<td><strong>Training data</strong></td>
<td>1.0T – 1.4T tokens (publicly available data)</td>
</tr>
<tr class="odd">
<td><strong>Key innovation</strong></td>
<td>Chinchilla-optimal training; open weights with commercial license</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Spawned thousands of open-source derivatives and fine-tunes</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“Our mission is to open up access to AI so that more people and institutions can explore, research, and benefit from it.” — Meta AI</p>
</blockquote>
<p>LLaMA’s release shattered the assumption that only closed-source labs could produce competitive language models. Within weeks, the open-source community produced <strong>Alpaca</strong>, <strong>Vicuna</strong>, <strong>WizardLM</strong>, and hundreds of fine-tuned variants. By 2024, open models regularly competed with proprietary ones on key benchmarks. In early 2025, <strong>DeepSeek-R1</strong> from China demonstrated that open reasoning models could match frontier performance, further validating the open-source approach.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["LLaMA&lt;br/&gt;(Feb 2023)&lt;br/&gt;Research License"] --&gt; B["Llama 2&lt;br/&gt;(Jul 2023)&lt;br/&gt;Commercial License"]
    B --&gt; C["Llama 3&lt;br/&gt;(Apr 2024)&lt;br/&gt;8B, 70B, 405B"]
    A --&gt; D["Open-Source&lt;br/&gt;Explosion"]
    D --&gt; E["Alpaca · Vicuna&lt;br/&gt;WizardLM"]
    D --&gt; F["Mistral · Mixtral&lt;br/&gt;Qwen · DeepSeek"]
    C --&gt; G["Narrowing Gap with&lt;br/&gt;Frontier Proprietary&lt;br/&gt;Models"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#2980b9,color:#fff,stroke:#333
    style C fill:#e74c3c,color:#fff,stroke:#333
    style D fill:#27ae60,color:#fff,stroke:#333
    style E fill:#f39c12,color:#fff,stroke:#333
    style F fill:#8e44ad,color:#fff,stroke:#333
    style G fill:#1a5276,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="generative-art-and-creative-ai-20222023" class="level2">
<h2 class="anchored" data-anchor-id="generative-art-and-creative-ai-20222023">Generative Art and Creative AI (2022–2023)</h2>
<p>By 2023, <strong>generative AI</strong> had become a cultural phenomenon. <strong>Midjourney</strong> — a text-to-image service accessible via Discord — produced images so stunning that a Midjourney-generated artwork won a prize at the Colorado State Fair art competition in September 2022, igniting fierce debate about the nature of creativity and authorship.</p>
<p><strong>DALL·E 3</strong> (October 2023) was integrated directly into ChatGPT, allowing users to generate and refine images through natural conversation. <strong>Stable Diffusion XL</strong> (July 2023) introduced native 1024×1024 resolution and dramatically improved image quality. And the open-source community built an ecosystem of tools — ControlNet, LoRA fine-tuning, ComfyUI — that gave artists and developers unprecedented control over the generation process.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Midjourney V5</strong></td>
<td>March 2023 — photorealistic quality</td>
</tr>
<tr class="even">
<td><strong>DALL·E 3</strong></td>
<td>October 2023 — integrated into ChatGPT</td>
</tr>
<tr class="odd">
<td><strong>Stable Diffusion XL</strong></td>
<td>July 2023 — 1024×1024, 3.5B parameters</td>
</tr>
<tr class="even">
<td><strong>Colorado controversy</strong></td>
<td>September 2022 — Midjourney artwork wins art prize</td>
</tr>
<tr class="odd">
<td><strong>Key tools</strong></td>
<td>ControlNet, LoRA, DreamBooth, ComfyUI, AUTOMATIC1111</td>
</tr>
<tr class="even">
<td><strong>Impact</strong></td>
<td>Democratized visual creation; challenged traditional art markets</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“AI-generated art is the most disruptive thing to happen to visual culture since the invention of photography.” — artist and critic Jason Allen, 2022</p>
</blockquote>
<p>Generative AI raised existential questions for creative professionals. Could AI replace artists, designers, and photographers? Was AI-generated content copyrightable? The legal and cultural debates intensified: the U.S. Copyright Office ruled that purely AI-generated images could not be copyrighted, while courts grappled with whether training on copyrighted data constituted fair use.</p>
</section>
<section id="microsoft-365-copilot-ai-in-enterprise-2023" class="level2">
<h2 class="anchored" data-anchor-id="microsoft-365-copilot-ai-in-enterprise-2023">Microsoft 365 Copilot: AI in Enterprise (2023)</h2>
<p>In March 2023, <strong>Microsoft</strong> announced <strong>Microsoft 365 Copilot</strong>, bringing GPT-4-powered AI assistance into Word, Excel, PowerPoint, Outlook, and Teams. This was a watershed moment: for the first time, large language models were embedded directly into the productivity tools used by <strong>hundreds of millions of knowledge workers</strong> worldwide.</p>
<p>Copilot could draft documents, summarize email threads, generate presentations from outlines, analyze spreadsheets with natural language queries, and take meeting notes in Teams. It demonstrated that LLMs could augment — rather than replace — human knowledge work.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Announced</strong></td>
<td>March 2023</td>
</tr>
<tr class="even">
<td><strong>General availability</strong></td>
<td>November 2023</td>
</tr>
<tr class="odd">
<td><strong>Powered by</strong></td>
<td>GPT-4, Microsoft Graph (user context)</td>
</tr>
<tr class="even">
<td><strong>Applications</strong></td>
<td>Word, Excel, PowerPoint, Outlook, Teams</td>
</tr>
<tr class="odd">
<td><strong>Pricing</strong></td>
<td>$30/user/month (enterprise)</td>
</tr>
<tr class="even">
<td><strong>Significance</strong></td>
<td>LLMs embedded in enterprise productivity at planetary scale</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“Copilot is not just a better autocomplete — it’s a new way of working, where AI and human intelligence amplify each other.” — Satya Nadella, CEO of Microsoft</p>
</blockquote>
<p>The launch of Microsoft 365 Copilot, alongside Google’s <strong>Duet AI for Workspace</strong> (later Gemini for Google Workspace), marked the beginning of the <strong>AI-augmented workplace</strong>. By 2024, AI assistance in documents, code, email, and data analysis was rapidly becoming the default expectation in enterprise environments.</p>
</section>
<section id="multimodal-ai-and-gpt-4o-2024" class="level2">
<h2 class="anchored" data-anchor-id="multimodal-ai-and-gpt-4o-2024">Multimodal AI and GPT-4o (2024)</h2>
<p>On <strong>May 13, 2024</strong>, OpenAI released <strong>GPT-4o</strong> (“o” for “omni”) — a model natively designed to process and generate <strong>text, audio, and images</strong> in a unified architecture. GPT-4o could engage in real-time voice conversations with human-like latency (~320 ms average response time), analyze images, and generate both text and audio outputs.</p>
<p>GPT-4o represented a fundamental shift from the chatbot paradigm to a <strong>multimodal assistant</strong> paradigm. It could understand tone, emotion, and context in voice conversations; describe and analyze visual scenes; and seamlessly switch between modalities — all at substantially faster speed and lower cost than GPT-4.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Released</strong></td>
<td>May 13, 2024</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>OpenAI</td>
</tr>
<tr class="odd">
<td><strong>Modalities</strong></td>
<td>Text + audio + image (input and output)</td>
</tr>
<tr class="even">
<td><strong>Response latency</strong></td>
<td>~320 ms (comparable to human conversation)</td>
</tr>
<tr class="odd">
<td><strong>Follow-ups</strong></td>
<td>GPT-4o mini (Jul 2024, cost-optimized)</td>
</tr>
<tr class="even">
<td><strong>Key advance</strong></td>
<td>Natively multimodal — not separate models stitched together</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Shifted AI from text chatbot to omni-modal real-time assistant</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“The technology is moving so fast — GPT-4o is the kind of AI interaction we used to see only in science fiction movies.” — tech reviewer reaction, May 2024</p>
</blockquote>
<p>Google’s <strong>Gemini</strong> models (2023–2024) pursued a parallel path toward natively multimodal architecture. By late 2024, the expectation for frontier AI systems was that they would be <strong>multimodal by default</strong> — understanding and generating across text, image, audio, and increasingly video.</p>
</section>
<section id="on-device-ai-and-model-efficiency-2024" class="level2">
<h2 class="anchored" data-anchor-id="on-device-ai-and-model-efficiency-2024">On-Device AI and Model Efficiency (2024)</h2>
<p>In 2024, the AI industry underwent a paradigm shift toward <strong>running capable language models directly on consumer devices</strong> — smartphones, laptops, and edge hardware — rather than relying solely on cloud APIs. <strong>Apple Intelligence</strong> brought on-device models to iPhones and Macs; <strong>Google</strong> embedded Gemini Nano into Pixel phones; and <strong>Qualcomm</strong>, <strong>Intel</strong>, and <strong>AMD</strong> shipped dedicated neural processing units (NPUs) optimized for transformer inference.</p>
<p>This shift was enabled by years of research into <strong>model compression techniques</strong>: quantization (reducing precision from 32-bit to 4-bit or lower), distillation (training smaller models to mimic larger ones), pruning, and efficient architectures like mixture-of-experts.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Apple Intelligence</strong></td>
<td>Announced June 2024, iOS 18 / macOS Sequoia</td>
</tr>
<tr class="even">
<td><strong>Gemini Nano</strong></td>
<td>Deployed on Pixel devices for on-device chat and summarization</td>
</tr>
<tr class="odd">
<td><strong>Hardware</strong></td>
<td>NPUs in Qualcomm Snapdragon, Intel Core Ultra, Apple M-series</td>
</tr>
<tr class="even">
<td><strong>Techniques</strong></td>
<td>Quantization (GPTQ, GGML, AWQ), distillation, pruning, LoRA adapters</td>
</tr>
<tr class="odd">
<td><strong>Models</strong></td>
<td>Phi-3 (Microsoft), Gemma (Google), Llama 3.2 (Meta) — designed for on-device</td>
</tr>
<tr class="even">
<td><strong>Significance</strong></td>
<td>AI inference without cloud dependency; privacy-preserving, low-latency</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“On-device AI means your AI assistant works even without an internet connection — and your data never leaves your phone.” — Apple, WWDC 2024</p>
</blockquote>
<p>On-device AI addressed critical concerns about <strong>privacy</strong>, <strong>latency</strong>, and <strong>cost</strong>. By running models locally, sensitive data never had to be transmitted to the cloud. And for developers, eliminating per-query API costs fundamentally changed the economics of AI-powered applications.</p>
</section>
<section id="ai-governance-and-the-eu-ai-act-2024" class="level2">
<h2 class="anchored" data-anchor-id="ai-governance-and-the-eu-ai-act-2024">AI Governance and the EU AI Act (2024)</h2>
<p>As AI capabilities accelerated, governments worldwide moved to establish <strong>regulatory frameworks</strong>. The most significant was the <strong>EU AI Act</strong>, which entered into force on <strong>August 1, 2024</strong> — the world’s first comprehensive legal framework for artificial intelligence.</p>
<p>The EU AI Act classified AI systems into risk tiers: <strong>unacceptable</strong> (banned — e.g., social scoring, real-time facial recognition in public spaces), <strong>high-risk</strong> (subject to strict requirements), <strong>limited risk</strong> (transparency obligations), and <strong>minimal risk</strong> (largely unregulated). General-purpose AI models like GPT-4 and Llama fell under specific provisions requiring transparency and documentation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>EU AI Act</strong></td>
<td>Entered into force August 1, 2024</td>
</tr>
<tr class="even">
<td><strong>U.S. Executive Order</strong></td>
<td>October 30, 2023 (AI safety and security)</td>
</tr>
<tr class="odd">
<td><strong>China AI regulations</strong></td>
<td>Generative AI rules effective August 2023</td>
</tr>
<tr class="even">
<td><strong>G7 Hiroshima AI Process</strong></td>
<td>International voluntary code of conduct</td>
</tr>
<tr class="odd">
<td><strong>Key principles</strong></td>
<td>Risk-based classification, transparency, human oversight</td>
</tr>
<tr class="even">
<td><strong>Frontier model provisions</strong></td>
<td>Safety testing, red-teaming, incident reporting</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>First comprehensive AI regulation; global template for governance</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“The AI Act is not about saying ‘no’ to AI — it’s about building trust so that AI can be adopted more widely.” — European Commission</p>
</blockquote>
<p>In parallel, AI companies adopted voluntary <strong>safety commitments</strong>: red-teaming, model evaluations, watermarking of AI-generated content, and responsible disclosure. The 2024 Nobel Prize for Chemistry (AlphaFold) and Physics (neural networks by Hinton and Hopfield) highlighted both AI’s transformative potential and the urgency of thoughtful governance.</p>
</section>
<section id="ai-agents-the-next-frontier-2025" class="level2">
<h2 class="anchored" data-anchor-id="ai-agents-the-next-frontier-2025">AI Agents: The Next Frontier (2025)</h2>
<p>By 2025, the focus of AI research and deployment shifted decisively toward <strong>agentic AI</strong> — systems that don’t just respond to queries but <strong>plan, reason, use tools, and execute multi-step tasks autonomously</strong>. AI agents could browse the web, write and execute code, manage files, call APIs, and chain together complex workflows with minimal human intervention.</p>
<p>OpenAI launched <strong>Operator</strong> (January 2025) for browser-based task automation, followed by <strong>Codex</strong> (May 2025) for autonomous software engineering, and a general-purpose <strong>ChatGPT Agent</strong> (July 2025). Google, Anthropic, and Microsoft deployed their own agent frameworks. The paradigm shifted from “chatbot you talk to” to “assistant that works for you.”</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>OpenAI Operator</strong></td>
<td>January 2025 — autonomous web browsing and task execution</td>
</tr>
<tr class="even">
<td><strong>OpenAI Codex agent</strong></td>
<td>May 2025 — autonomous software engineering</td>
</tr>
<tr class="odd">
<td><strong>ChatGPT Agent</strong></td>
<td>July 2025 — general-purpose task agent</td>
</tr>
<tr class="even">
<td><strong>Anthropic Claude</strong></td>
<td>Tool use, computer use, multi-step reasoning capabilities</td>
</tr>
<tr class="odd">
<td><strong>Google Project Mariner</strong></td>
<td>Agent framework for complex task delegation</td>
</tr>
<tr class="even">
<td><strong>Key capabilities</strong></td>
<td>Planning, tool use, code execution, multi-step reasoning, memory</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Shift from conversational AI to autonomous task execution</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“We’re moving from AI that answers questions to AI that actually does things for you.” — Dario Amodei, CEO of Anthropic</p>
</blockquote>
<p>The agentic paradigm brought new challenges: reliability (agents could make mistakes that compound over multiple steps), safety (autonomous actions require guardrails), and trust (users needed confidence that agents would act within approved boundaries). But the potential was enormous: AI agents promised to automate entire workflows — from research and data analysis to coding, scheduling, and content creation — fundamentally reshaping knowledge work.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["User Intent&lt;br/&gt;(Natural Language)"] --&gt; B["Planning Module&lt;br/&gt;(Decompose into Steps)"]
    B --&gt; C["Tool Selection&lt;br/&gt;(APIs, Code, Browser)"]
    C --&gt; D["Execution&lt;br/&gt;(Multi-step Actions)"]
    D --&gt; E["Observation&lt;br/&gt;&amp; Reflection"]
    E --&gt;|"Iterate"| B
    E --&gt; F["Final Result&lt;br/&gt;Delivered to User"]

    style A fill:#3498db,color:#fff,stroke:#333
    style B fill:#e74c3c,color:#fff,stroke:#333
    style C fill:#27ae60,color:#fff,stroke:#333
    style D fill:#f39c12,color:#fff,stroke:#333
    style E fill:#8e44ad,color:#fff,stroke:#333
    style F fill:#1a5276,color:#fff,stroke:#333
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="deepseek-and-the-open-reasoning-revolution-2025" class="level2">
<h2 class="anchored" data-anchor-id="deepseek-and-the-open-reasoning-revolution-2025">DeepSeek and the Open Reasoning Revolution (2025)</h2>
<p>In January 2025, Chinese AI lab <strong>DeepSeek</strong> released <strong>DeepSeek-R1</strong> — an open-weight reasoning model that matched or exceeded the performance of OpenAI’s o1 on mathematics, coding, and scientific reasoning benchmarks. DeepSeek-R1 was notable for its transparency: it explicitly showed its chain-of-thought reasoning process, and its weights were freely available.</p>
<p>DeepSeek’s breakthrough demonstrated that frontier AI capabilities were no longer the exclusive domain of a handful of well-funded Western labs. It also validated the viability of <strong>open reasoning models</strong> — LLMs that could perform extended multi-step reasoning with full weight availability for the research community.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Released</strong></td>
<td>January 2025</td>
</tr>
<tr class="even">
<td><strong>Developer</strong></td>
<td>DeepSeek (China)</td>
</tr>
<tr class="odd">
<td><strong>Key models</strong></td>
<td>DeepSeek-V3, DeepSeek-R1 (reasoning)</td>
</tr>
<tr class="even">
<td><strong>R1 performance</strong></td>
<td>Competitive with OpenAI o1 on math, code, and science</td>
</tr>
<tr class="odd">
<td><strong>Training efficiency</strong></td>
<td>Reportedly trained at significantly lower cost than Western models</td>
</tr>
<tr class="even">
<td><strong>License</strong></td>
<td>Open weights</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Proved open models could match frontier reasoning capabilities</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“DeepSeek-R1 reminded the world that AI innovation is global — and that openness accelerates progress.” — AI researcher reaction, January 2025</p>
</blockquote>
<p>DeepSeek’s success intensified the global race in AI development and prompted Western labs to accelerate their own reasoning model efforts. OpenAI responded with <strong>o3</strong> (April 2025), and the competition between open and closed reasoning models became one of the defining dynamics of the AI landscape.</p>
</section>
<section id="text-to-video-and-the-expanding-creative-frontier-20242025" class="level2">
<h2 class="anchored" data-anchor-id="text-to-video-and-the-expanding-creative-frontier-20242025">Text-to-Video and the Expanding Creative Frontier (2024–2025)</h2>
<p>As image generation matured, the frontier moved to <strong>video</strong>. In February 2024, OpenAI previewed <strong>Sora</strong> — a diffusion transformer model that could generate realistic minute-long videos from text prompts. Sora produced coherent, cinematic footage with consistent characters, camera movements, and physical interactions that far surpassed previous video generation attempts.</p>
<p>By 2025, multiple labs had released video generation models: Google’s <strong>Veo</strong>, Runway’s <strong>Gen-3</strong>, and open-source alternatives. While none matched Hollywood production quality, they represented a paradigm shift — the ability to generate visual narratives from text descriptions, with implications for filmmaking, advertising, education, and entertainment.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Details</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sora preview</strong></td>
<td>February 2024 (OpenAI)</td>
</tr>
<tr class="even">
<td><strong>Sora public release</strong></td>
<td>December 2024</td>
</tr>
<tr class="odd">
<td><strong>Competitors</strong></td>
<td>Google Veo, Runway Gen-3, Pika, Kling</td>
</tr>
<tr class="even">
<td><strong>Capabilities</strong></td>
<td>Minute-long coherent video from text prompts</td>
</tr>
<tr class="odd">
<td><strong>Technical approach</strong></td>
<td>Diffusion transformer trained on video data</td>
</tr>
<tr class="even">
<td><strong>Challenges</strong></td>
<td>Physics consistency, long-form coherence, compute cost</td>
</tr>
<tr class="odd">
<td><strong>Significance</strong></td>
<td>Extended generative AI from static images to temporal narratives</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>“The leap from image generation to video generation is like going from photography to cinema — it opens up entirely new forms of expression.”</p>
</blockquote>
<p>Text-to-video, alongside advances in <strong>3D generation</strong> and <strong>world models</strong>, pointed toward a future where AI could generate entire virtual environments, interactive experiences, and personalized media on demand.</p>
</section>
<section id="the-20202025-transformation-at-a-glance" class="level2">
<h2 class="anchored" data-anchor-id="the-20202025-transformation-at-a-glance">The 2020–2025 Transformation at a Glance</h2>
<p>The half-decade from 2020 to 2025 transformed AI from a powerful but specialized technology into a <strong>general-purpose tool reshaping civilization</strong>. The speed and breadth of change was without precedent:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>2019 State</th>
<th>2025 State</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Largest language model</strong></td>
<td>GPT-2 (1.5B parameters)</td>
<td>GPT-5, Gemini Ultra, Claude, Llama 3.1 (100B–1T+)</td>
</tr>
<tr class="even">
<td><strong>Chat AI users</strong></td>
<td>Virtually none</td>
<td>Hundreds of millions weekly</td>
</tr>
<tr class="odd">
<td><strong>Image generation</strong></td>
<td>Research demos</td>
<td>Billions of images generated; integrated into consumer apps</td>
</tr>
<tr class="even">
<td><strong>Video generation</strong></td>
<td>Primitive</td>
<td>Minute-long coherent videos from text</td>
</tr>
<tr class="odd">
<td><strong>Code generation</strong></td>
<td>Auto-complete</td>
<td>Autonomous coding agents</td>
</tr>
<tr class="even">
<td><strong>AI in science</strong></td>
<td>Promising early results</td>
<td>Nobel Prize–winning breakthroughs (AlphaFold)</td>
</tr>
<tr class="odd">
<td><strong>AI regulation</strong></td>
<td>Minimal</td>
<td>EU AI Act, executive orders, international frameworks</td>
</tr>
<tr class="even">
<td><strong>On-device AI</strong></td>
<td>None</td>
<td>Full language models running on smartphones</td>
</tr>
<tr class="odd">
<td><strong>AI agents</strong></td>
<td>Concept/research</td>
<td>Deployed agent products (Operator, Copilot, Codex)</td>
</tr>
<tr class="even">
<td><strong>Industry investment</strong></td>
<td>Billions annually</td>
<td>Hundreds of billions annually</td>
</tr>
</tbody>
</table>
<p>By 2025, AI was no longer a future technology. It was the present — woven into search, creativity, productivity, science, governance, and daily life. And the pace showed no signs of slowing.</p>
</section>
<section id="video-20202025-ai-milestones-chatgpt-moments-generative-ai-agentic-ai" class="level2">
<h2 class="anchored" data-anchor-id="video-20202025-ai-milestones-chatgpt-moments-generative-ai-agentic-ai">Video: 2020–2025 AI Milestones — ChatGPT Moments, Generative AI &amp; Agentic AI</h2>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/9Z-tT2LteO4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<blockquote class="blockquote">
<p>Please subscribe to the <a href="https://www.youtube.com/@vectoringai">Vectoring AI YouTube channel</a> for more video tutorials 🚀</p>
</blockquote>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Brown, T. et al.&nbsp;“Language Models Are Few-Shot Learners.” <em>Advances in Neural Information Processing Systems</em> 33 (2020). <a href="https://arxiv.org/abs/2005.14165">arXiv:2005.14165</a></li>
<li>Dosovitskiy, A. et al.&nbsp;“An Image is Worth 16×16 Words: Transformers for Image Recognition at Scale.” <em>ICLR</em> (2021). <a href="https://arxiv.org/abs/2010.11929">arXiv:2010.11929</a></li>
<li>Jumper, J. et al.&nbsp;“Highly Accurate Protein Structure Prediction with AlphaFold.” <em>Nature</em> 596, 583–589 (2021).</li>
<li>Radford, A. et al.&nbsp;“Learning Transferable Visual Models From Natural Language Supervision.” <em>ICML</em> (2021). <a href="https://arxiv.org/abs/2103.00020">arXiv:2103.00020</a></li>
<li>Ouyang, L. et al.&nbsp;“Training Language Models to Follow Instructions with Human Feedback.” <em>NeurIPS</em> 35 (2022). <a href="https://arxiv.org/abs/2203.02155">arXiv:2203.02155</a></li>
<li>Hoffmann, J. et al.&nbsp;“Training Compute-Optimal Large Language Models.” <em>NeurIPS</em> 35 (2022). <a href="https://arxiv.org/abs/2203.15556">arXiv:2203.15556</a></li>
<li>Rombach, R. et al.&nbsp;“High-Resolution Image Synthesis with Latent Diffusion Models.” <em>CVPR</em> (2022). <a href="https://arxiv.org/abs/2112.10752">arXiv:2112.10752</a></li>
<li>Wei, J. et al.&nbsp;“Chain-of-Thought Prompting Elicits Reasoning in Large Language Models.” <em>NeurIPS</em> 35 (2022). <a href="https://arxiv.org/abs/2201.11903">arXiv:2201.11903</a></li>
<li>OpenAI. “GPT-4 Technical Report.” <em>arXiv:2303.08774</em> (2023).</li>
<li>Kirillov, A. et al.&nbsp;“Segment Anything.” <em>ICCV</em> (2023). <a href="https://arxiv.org/abs/2304.02643">arXiv:2304.02643</a></li>
<li>Touvron, H. et al.&nbsp;“LLaMA: Open and Efficient Foundation Language Models.” <em>arXiv:2302.13971</em> (2023).</li>
<li>Touvron, H. et al.&nbsp;“Llama 2: Open Foundation and Fine-Tuned Chat Models.” <em>arXiv:2307.09288</em> (2023).</li>
<li>Abramson, J. et al.&nbsp;“Accurate Structure Prediction of Biomolecular Interactions with AlphaFold 3.” <em>Nature</em> 630, 493–500 (2024).</li>
<li>Wikipedia. “ChatGPT.” <a href="https://en.wikipedia.org/wiki/ChatGPT">en.wikipedia.org/wiki/ChatGPT</a></li>
<li>Wikipedia. “AlphaFold.” <a href="https://en.wikipedia.org/wiki/AlphaFold">en.wikipedia.org/wiki/AlphaFold</a></li>
<li>Wikipedia. “Stable Diffusion.” <a href="https://en.wikipedia.org/wiki/Stable_Diffusion">en.wikipedia.org/wiki/Stable_Diffusion</a></li>
</ul>
</section>
<section id="read-more" class="level2">
<h2 class="anchored" data-anchor-id="read-more">Read More</h2>
<ul>
<li>See the decade of deep learning that preceded the generative AI era — <a href="../..\posts/milestone/2010s AI Milestones.html">2010s AI Milestones</a></li>
<li>The infrastructure decade that enabled modern AI — <a href="../..\posts/milestone/2000s AI Milestones.html">2000s AI Milestones</a></li>
<li>The data revolution and statistical learning — <a href="../..\posts/milestone/1990s AI Milestones.html">1990s AI Milestones</a></li>
<li>From expert systems to the second AI winter — <a href="../..\posts/milestone/1980s AI Milestones.html">1980s AI Milestones</a></li>
<li>The first AI winter and the seeds of recovery — <a href="../..\posts/milestone/1970s AI Milestones.html">1970s AI Milestones</a></li>
<li>Where it all began — <a href="../..\posts/milestone/1950s-1960s AI Milestones.html">1950s–1960s AI Milestones</a></li>
<li>How transformers power modern language models — <a href="../..\posts/llm/Pre-training LLMs from Scratch.html">Pre-training LLMs from Scratch</a></li>
<li>Modern methods for aligning LLMs — <a href="../..\posts/llm/Post-Training LLMs for Human Alignment.html">Post-Training LLMs for Human Alignment</a></li>
<li>From prompts to context — <a href="../..\posts/llm/Prompt Engineering vs Context Engineering.html">Prompt Engineering vs Context Engineering</a></li>
<li>Scaling inference for production — <a href="../..\posts/llm/Scaling LLM Serving for Enterprise Production.html">Scaling LLM Serving for Enterprise Production</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/vectoringai\.com\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><i class="fa-regular fa-copyright" aria-label="copyright"></i> 2025-2026 Vectoring AI. All rights reserved. | <a href="../..\pages/privacy.html">Privacy Policy</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>